### PR TITLE
Semaphore badge

### PR DESCRIPTION
**Pull request by such**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/363)

### CODE REVIEW

**Comment by simonvadee** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/363#-:-L7OroPXXmIqVLggiOu3:bnfp4nl)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[README.md, line 11 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/363#-L7OsHRdnL9G4Kfk-r7W:-L7OsHRdnL9G4Kfk-r7X:b-alsh5u) ([raw file](https://github.com/stratumn/go-indigocore/blob/f38e9585864ef61387fea88e91d59e392f4f45de/README.md#L11)):*
> ```Markdown
> [codecov](https://codecov.io/gh/stratumn/go-indigocore)
> [Go Report Card](https://goreportcard.com/report/github.com/stratumn/go-indigocore)
> [Join the chat at https://gitter.im/stratumn/sdk](https://gitter.im/stratumn/sdk?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)
> ```

Is it possible to rename gitter's sdk to indigocore?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/363#-:-L7OryLaMepoMvyt3HcM:bnfp4nl)*

**Comment by such** [comment]
*[README.md, line 11 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/363#-L7OsHRdnL9G4Kfk-r7W:-L7Ot5nL2A3mjcLhbU44:be2q1su) ([raw file](https://github.com/stratumn/go-indigocore/blob/f38e9585864ef61387fea88e91d59e392f4f45de/README.md#L11)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Is it possible to rename gitter's sdk to indigocore?
</blockquote></details>

renaming repo is a bit painful in gitter. we would lose all members: https://gitter.im/gitterHQ/topics/topic/580ef9ea472236f05c9e4788/what-happens-if-i-rename-something-on-github-org-repo
we might decide to do it anyway someday.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/363)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 11 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/363#-L7OsHRdnL9G4Kfk-r7W:-L7OtV4j9Fi9r1iG-bx3:b2w08lw) ([raw file](https://github.com/stratumn/go-indigocore/blob/f38e9585864ef61387fea88e91d59e392f4f45de/README.md#L11)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

renaming repo is a bit painful in gitter. we would lose all members: https://gitter.im/gitterHQ/topics/topic/580ef9ea472236f05c9e4788/what-happens-if-i-rename-something-on-github-org-repo
we might decide to do it anyway someday.
</blockquote></details>

Ok, it's better to keep `sdk`

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/363)*

**Comment by t-bast** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/363#-:-L7OtjUcBxD7j0GPY6cA:bg7igkv)*

**Pull request merged**
