### PR TITLE
tendermint: upgrade to 0.16.0

### PR DESCRIPTION
**Pull request by simonvadee**
### There are two noticeable changes:

- `Commit()` return value does not have `Code` and `Log` anymore : we have to return an empty `ResponseCommit` if an error occurred.

- Subscribing twice to a tendermint event (ie: NewBlock event) causes an error. Also, unsubscribing  when there is no current subscription causes an error.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/350)

### CODE REVIEW

**Comment by t-bast** [comment]
Neat, 3 minor versions in one shot! GG!
:lgtm: 

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tmstore/tmstore.go, line 116 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/350#-L5tAzf699xvDFtL55zu:-L5tAzf699xvDFtL55zv:bqp4qc0) ([raw file](https://github.com/stratumn/go-indigocore/blob/fce1ec1255b654adbb545c90735c911dbe759ecb/tmstore/tmstore.go#L116)):*
> ```Go
> 	}()
> 
> 	if err := t.tmClient.Subscribe(t.ctx, Name, tmtypes.EventQueryNewBlock, t.tmEventChan); err != nil && err.Error() != ErrAlreadySubscribed {
> ```

Can't you use their value for that error? Unless they don't expose it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/350#-:-L5tBMFOXt_IFRMMdC8e:b-44an09)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tmpop/tmpop.go, line 211 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/350#-L5tAKwk3ODbSwtLJ__z:-L5tAKwk3ODbSwtLJ_a-:brmv1sd) ([raw file](https://github.com/stratumn/go-indigocore/blob/fce1ec1255b654adbb545c90735c911dbe759ecb/tmpop/tmpop.go#L211)):*
> ```Go
> 	appHash, links, err := t.state.Commit()
> 	if err != nil {
> 		log.Errorf("Error while committing: %s", err.Error())
> ```

nit: `.Error()` is not necessary

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/350#-:-L5tBoK3ViTQk572Tg3V:bnfp4nl)*

**Comment by such** [comment]
:lgtm:
now you can update the tmpop-explorer \o/

---

Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/350#-:-L5tCBGjni8DpOvnIwk5:b-anua60)*

**Comment by alexppxela** [comment]
You did not expose the new flag: `--p2p.persistent_peers`.
It maybe will fix our problem of unsafe mode fore dial_seeds

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/350#-:-L5tCar54oTbTkgBe9Qr:bupkatk)*

**Comment by simonvadee** [comment]
@alexppxela you're right ! I'll look into it

---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tmpop/tmpop.go, line 211 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/350#-L5tAKwk3ODbSwtLJ__z:-L5tRiNKqaaGYdnuFoG_:bp8ocxv) ([raw file](https://github.com/stratumn/go-indigocore/blob/fce1ec1255b654adbb545c90735c911dbe759ecb/tmpop/tmpop.go#L211)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

nit: `.Error()` is not necessary
</blockquote></details>

:+1: Done

---

*[tmstore/tmstore.go, line 116 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/350#-L5tAzf699xvDFtL55zu:-L5tRcIPL9xmJZEyqfMZ:bii8c7r) ([raw file](https://github.com/stratumn/go-indigocore/blob/fce1ec1255b654adbb545c90735c911dbe759ecb/tmstore/tmstore.go#L116)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Can't you use their value for that error? Unless they don't expose it?
</blockquote></details>

the error message is hardcoded \o/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/350#-:-L5tSWWlQMENIalCDcdX:bfwwag9)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[tmstore/tmstore.go, line 116 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/350#-L5tAzf699xvDFtL55zu:-L5wcbOpDMA_gmm4QxK1:bfswp2j) ([raw file](https://github.com/stratumn/go-indigocore/blob/fce1ec1255b654adbb545c90735c911dbe759ecb/tmstore/tmstore.go#L116)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

the error message is hardcoded \o/
</blockquote></details>

Damn :(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/350#-:-L5wceDfJzfX66TAsTm6:bnfp4nl)*

**Comment by alexppxela** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/350)*

**Comment by t-bast** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/350)*

**Comment by alexppxela** [comment]
Perfect, we can perform some tests to check if there is auto-reconnection on persistent list of peers
:lgtm: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/350#-:-L5xwSmOmLZY9N15a-q6:b2doqfh)*

**Pull request merged**
