### PR TITLE
add elastic search store

### PR DESCRIPTION
**Pull request by jeremie-stratumn**
inspired by couchstore impl
tests (store + tmpop) run in ~30sec
I am using this elastic client in go: https://github.com/olivere/elastic

fix https://github.com/stratumn/go-indigocore/issues/349

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/357)

### CODE REVIEW

**Comment by such** [comment]
Good job! Sorry for the nitpicking...

---

Reviewed 8 of 8 files at r1.
Review status: 7 of 8 files reviewed at latest revision, 6 unresolved discussions.

---

*[elasticsearchstore/api.go, line 37 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6w-bag4czUqK7QmBm5:-L6w-bag4czUqK7QmBm6:b-ivw6io) ([raw file](https://github.com/stratumn/go-indigocore/blob/0a382d7b450b51e445d157641d06b79b7a68dfa4/elasticsearchstore/api.go#L37)):*
> ```Go
> 
> // Evidences is a wrapper around cs.Evidences for json ElasticSearch serialization compliance
> // Elastic Search does not allow indexing of arrays directly..
> ```

nit: only 1 dot

---

*[elasticsearchstore/api.go, line 43 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6w-ja5xeIZSQ2_aNwz:-L6w-ja5xeIZSQ2_aNx-:bqyzknl) ([raw file](https://github.com/stratumn/go-indigocore/blob/0a382d7b450b51e445d157641d06b79b7a68dfa4/elasticsearchstore/api.go#L43)):*
> ```Go
> 
> // Value is a wrapper struct for the value of the keyvalue store part
> // Elastic only accepts json structured objects
> ```

nit: we're trying to end comments with a dot.

---

*[elasticsearchstore/api.go, line 61 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6w006roMikReH1vQl7:-L6w006roMikReH1vQl8:bvjx4tr) ([raw file](https://github.com/stratumn/go-indigocore/blob/0a382d7b450b51e445d157641d06b79b7a68dfa4/elasticsearchstore/api.go#L61)):*
> ```Go
> 		if !createIndex.Acknowledged {
> 			// Not acknowledged
> 			return fmt.Errorf("Error creating %s index", indexName)
> ```

nit: errors should be in lower case.

---

*[elasticsearchstore/elasticsearchstore.go, line 68 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6w0wQHRLOrVJmxx10P:-L6w0wQHRLOrVJmxx10Q:bw7kvpf) ([raw file](https://github.com/stratumn/go-indigocore/blob/0a382d7b450b51e445d157641d06b79b7a68dfa4/elasticsearchstore/elasticsearchstore.go#L68)):*
We're trying to follow the best pratice for context even if that feels a bit inconfortable:
> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx:

https://golang.org/pkg/context/

---

*[elasticsearchstore/elasticsearchstore.go, line 205 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6w1jS4A-NYYr9GDASV:-L6w1jS4A-NYYr9GDASW:bojco44) ([raw file](https://github.com/stratumn/go-indigocore/blob/0a382d7b450b51e445d157641d06b79b7a68dfa4/elasticsearchstore/elasticsearchstore.go#L205)):*
> ```Go
> }
> 
> /********** github.com/stratumn/go-indigocore/store.KeyValueStore implementation **********/
> ```

I'm not sure this was really needed but I guess it can be useful at some point. It doesn't seem to bloat the code too much.

---

*[elasticsearchstore/elasticsearchstore_test.go, line 77 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6w2303wyIXu5X2pxAT:-L6w2303wyIXu5X2pxAU:b4wcodr) ([raw file](https://github.com/stratumn/go-indigocore/blob/0a382d7b450b51e445d157641d06b79b7a68dfa4/elasticsearchstore/elasticsearchstore_test.go#L77)):*
> ```Go
> 		fmt.Printf(err.Error())
> 		os.Exit(1)
> 	}
> ```

nit: we could probably factorize this code at some point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-:-L6w2E6Qw9SfjQCNmlPT:b-y945kx)*

**Comment by such** [comment]
Review status: 7 of 8 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[elasticsearchstore/elasticsearchstore_test.go, line 95 at r2](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6w4Yh_ycj3i5KQTM2R:-L6w4Yh_ycj3i5KQTM2S:b-xg3hci) ([raw file](https://github.com/stratumn/go-indigocore/blob/af39fddd2241f38838a04dc602ac4a9884e099d7/elasticsearchstore/elasticsearchstore_test.go#L95)):*
> ```Go
> 
> func TestElasticSearchStore(t *testing.T) {
> 	if *integration {
> ```

do we really want to consider this test as integration?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/357)*

**Comment by such** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/357)*

**Comment by jeremie-stratumn** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[elasticsearchstore/api.go, line 37 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6w-bag4czUqK7QmBm5:-L6wJ_omglMSzIvkOFYg:b32wtd) ([raw file](https://github.com/stratumn/go-indigocore/blob/0a382d7b450b51e445d157641d06b79b7a68dfa4/elasticsearchstore/api.go#L37)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

nit: only 1 dot
</blockquote></details>

ok

---

*[elasticsearchstore/api.go, line 43 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6w-ja5xeIZSQ2_aNwz:-L6wJZdGi7fCbTBvAyC5:b-q8ilnv) ([raw file](https://github.com/stratumn/go-indigocore/blob/0a382d7b450b51e445d157641d06b79b7a68dfa4/elasticsearchstore/api.go#L43)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

nit: we're trying to end comments with a dot.
</blockquote></details>

gotcha

---

*[elasticsearchstore/api.go, line 61 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6w006roMikReH1vQl7:-L6wJYheF0PA_9TPYCXB:b-q8ilnv) ([raw file](https://github.com/stratumn/go-indigocore/blob/0a382d7b450b51e445d157641d06b79b7a68dfa4/elasticsearchstore/api.go#L61)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

nit: errors should be in lower case.
</blockquote></details>

gotcha

---

*[elasticsearchstore/elasticsearchstore.go, line 68 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6w0wQHRLOrVJmxx10P:-L6wJVz5uVwLAnXh5YfT:b-v5utkw) ([raw file](https://github.com/stratumn/go-indigocore/blob/0a382d7b450b51e445d157641d06b79b7a68dfa4/elasticsearchstore/elasticsearchstore.go#L68)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

We're trying to follow the best pratice for context even if that feels a bit inconfortable:
> Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it. The Context should be the first parameter, typically named ctx:

https://golang.org/pkg/context/


</blockquote></details>

I see, I'll change that

---

*[elasticsearchstore/elasticsearchstore.go, line 205 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6w1jS4A-NYYr9GDASV:-L6wJIiw6JGLxNGFQgCl:b-21ze06) ([raw file](https://github.com/stratumn/go-indigocore/blob/0a382d7b450b51e445d157641d06b79b7a68dfa4/elasticsearchstore/elasticsearchstore.go#L205)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I'm not sure this was really needed but I guess it can be useful at some point. It doesn't seem to bloat the code too much.
</blockquote></details>

You mean that ESStore does not need to be a KeyValueStore? When do we use KVStore? Tests would fail if not implemented I suppose?

---

*[elasticsearchstore/elasticsearchstore_test.go, line 77 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6w2303wyIXu5X2pxAT:-L6wJHl0-VTodQ7Es2wb:b-t77xc3) ([raw file](https://github.com/stratumn/go-indigocore/blob/0a382d7b450b51e445d157641d06b79b7a68dfa4/elasticsearchstore/elasticsearchstore_test.go#L77)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

nit: we could probably factorize this code at some point.
</blockquote></details>

agreed

---

*[elasticsearchstore/elasticsearchstore_test.go, line 95 at r2](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6w4Yh_ycj3i5KQTM2R:-L6wIvDuNa_o3FGuJUXv:b-uinpyl) ([raw file](https://github.com/stratumn/go-indigocore/blob/af39fddd2241f38838a04dc602ac4a9884e099d7/elasticsearchstore/elasticsearchstore_test.go#L95)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

do we really want to consider this test as integration?
</blockquote></details>

I had all sorts of problems on travis and semaphore CI:
https://semaphoreci.com/stratumn/go-indigocore/branches/jd-elasticsearchstore/builds/1
https://travis-ci.org/stratumn/go-indigocore/builds/349873828?utm_source=github_status&utm_medium=notification

the travis error means that it takes too long to even start elasticsearch container..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/357)*

**Comment by bejito** [comment]
*[elasticsearchstore/api.go, line 265 at r2](https://beta.reviewable.io/reviews/stratumn/go-indigocore/357#-L6wH7Xz3YDQYjHbULXH:-L6wGpaJDqNAlI_eG4a9:b-l2yz4d) ([raw file](https://github.com/stratumn/go-indigocore/blob/af39fddd2241f38838a04dc602ac4a9884e099d7/elasticsearchstore/api.go#L265)):*
> ```Go
> 		}
> 	}
> 	return filter.PaginateStrings(res), nil
> ```

Shouldn't we directly paginate the call to ES ?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/357)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[elasticsearchstore/elasticsearchstore.go, line 205 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6w1jS4A-NYYr9GDASV:-L6wKoym7Vgd8SoM1VPY:bu8yxze) ([raw file](https://github.com/stratumn/go-indigocore/blob/0a382d7b450b51e445d157641d06b79b7a68dfa4/elasticsearchstore/elasticsearchstore.go#L205)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

You mean that ESStore does not need to be a KeyValueStore? When do we use KVStore? Tests would fail if not implemented I suppose?
</blockquote></details>

No you're right. Right now I don't think there's a way to test only the LinkStore. But the KVStore is only used in tmpop and we have a generic implementation.

---

*[elasticsearchstore/elasticsearchstore_test.go, line 95 at r2](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6w4Yh_ycj3i5KQTM2R:-L6wL1cOgjStjuLoHma1:b2nh4dy) ([raw file](https://github.com/stratumn/go-indigocore/blob/af39fddd2241f38838a04dc602ac4a9884e099d7/elasticsearchstore/elasticsearchstore_test.go#L95)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

I had all sorts of problems on travis and semaphore CI:
https://semaphoreci.com/stratumn/go-indigocore/branches/jd-elasticsearchstore/builds/1
https://travis-ci.org/stratumn/go-indigocore/builds/349873828?utm_source=github_status&utm_medium=notification

the travis error means that it takes too long to even start elasticsearch container..
</blockquote></details>

:'(

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/357)*

**Comment by jeremie-stratumn** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[elasticsearchstore/api.go, line 265 at r2](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6wH7Xz3YDQYjHbULXH:-L6wMOTz8PYn4yPONCz5:b-2wcusk) ([raw file](https://github.com/stratumn/go-indigocore/blob/af39fddd2241f38838a04dc602ac4a9884e099d7/elasticsearchstore/api.go#L265)):*
<details><summary><i>Previously, bejito (Mourad BEJI) wrote…</i></summary><blockquote>

Shouldn't we directly paginate the call to ES ?
</blockquote></details>

I dont know that this is possible...
https://discuss.elastic.co/t/pagination-in-aggregation/79423
https://github.com/elastic/elasticsearch/issues/4915
https://github.com/elastic/elasticsearch/issues/21487

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/357)*

**Comment by bejito** [comment]
*[elasticsearchstore/api.go, line 265 at r2](https://beta.reviewable.io/reviews/stratumn/go-indigocore/357#-L6wH7Xz3YDQYjHbULXH:-L6wO4sq2E56wWnRUtvV:b-k5ahms) ([raw file](https://github.com/stratumn/go-indigocore/blob/af39fddd2241f38838a04dc602ac4a9884e099d7/elasticsearchstore/api.go#L265)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

I dont know that this is possible...
https://discuss.elastic.co/t/pagination-in-aggregation/79423
https://github.com/elastic/elasticsearch/issues/4915
https://github.com/elastic/elasticsearch/issues/21487
</blockquote></details>

indeed... 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/357)*

**Comment by alexppxela** [comment]
Great!

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions, some commit checks failed.

---

*[elasticsearchstore/api.go, line 291 at r2](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6zgWuiCUzccDtvK5Wu:-L6zgWuiCUzccDtvK5Wv:bf2bjv9) ([raw file](https://github.com/stratumn/go-indigocore/blob/af39fddd2241f38838a04dc602ac4a9884e099d7/elasticsearchstore/api.go#L291)):*
> ```Go
> 	// prevLinkHash filter
> 	if filter.PrevLinkHash != nil {
> 		if len(*filter.PrevLinkHash) > 0 {
> ```

nit: it's more usual to test `if *filter.PrevLinkHash != ""` in go than `len(...) > 0`

---

*[elasticsearchstore/api.go, line 302 at r2](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6zi5Ty_KyWQcfs4gne:-L6zi5Ty_KyWQcfs4gnf:b-im5s3n) ([raw file](https://github.com/stratumn/go-indigocore/blob/af39fddd2241f38838a04dc602ac4a9884e099d7/elasticsearchstore/api.go#L302)):*
> ```Go
> 
> 	// process filter
> 	if len(filter.Process) > 0 {
> ```

Idem for checking emptiness

---

*[elasticsearchstore/elasticsearchstore.go, line 141 at r2](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-L6zn0pTc1XPiHO7JXYr:-L6zn0pTc1XPiHO7JXYs:bqroq3b) ([raw file](https://github.com/stratumn/go-indigocore/blob/af39fddd2241f38838a04dc602ac4a9884e099d7/elasticsearchstore/elasticsearchstore.go#L141)):*
> ```Go
> // AddStoreEventChannel implements github.com/stratumn/go-indigocore/store.Adapter.AddStoreEventChannel
> func (es *ESStore) AddStoreEventChannel(eventChan chan *store.Event) {
> 	es.eventChans = append(es.eventChans, eventChan)
> ```

eventChans is not concurrent protected. It is the case for all stores...
`AddStoreEventChannel` is only called at storehttp startup, there is no race condition but we have to keep it in mind for later (check trace usage)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-:-L6zokHni40th3aAdWKd:btojbfd)*

**Comment by jeremie-stratumn** [comment]
Review status: 4 of 8 files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[elasticsearchstore/api.go, line 291 at r2](https://beta.reviewable.io/reviews/stratumn/go-indigocore/357#-L6zgWuiCUzccDtvK5Wu:-L7-6KVd9sjS8GNyo9Qu:bb7f2mf) ([raw file](https://github.com/stratumn/go-indigocore/blob/af39fddd2241f38838a04dc602ac4a9884e099d7/elasticsearchstore/api.go#L291)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

nit: it's more usual to test `if *filter.PrevLinkHash != ""` in go than `len(...) > 0`
</blockquote></details>

done

---

*[elasticsearchstore/api.go, line 302 at r2](https://beta.reviewable.io/reviews/stratumn/go-indigocore/357#-L6zi5Ty_KyWQcfs4gne:-L7-6MlS57xw_xtgu6Gn:bb7f2mf) ([raw file](https://github.com/stratumn/go-indigocore/blob/af39fddd2241f38838a04dc602ac4a9884e099d7/elasticsearchstore/api.go#L302)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Idem for checking emptiness
</blockquote></details>

done

---

*[elasticsearchstore/elasticsearchstore.go, line 68 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/357#-L6w0wQHRLOrVJmxx10P:-L7-6nP518XswH2IOxER:bb7f2mf) ([raw file](https://github.com/stratumn/go-indigocore/blob/0a382d7b450b51e445d157641d06b79b7a68dfa4/elasticsearchstore/elasticsearchstore.go#L68)):*
<details><summary><i>Previously, jeremie-stratumn (Jeremie Dayan) wrote…</i></summary><blockquote>

I see, I'll change that
</blockquote></details>

done

---

*[elasticsearchstore/elasticsearchstore.go, line 205 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/357#-L6w1jS4A-NYYr9GDASV:-L7-6pzW5FIpVfqs_aP0:b32wtd) ([raw file](https://github.com/stratumn/go-indigocore/blob/0a382d7b450b51e445d157641d06b79b7a68dfa4/elasticsearchstore/elasticsearchstore.go#L205)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

No you're right. Right now I don't think there's a way to test only the LinkStore. But the KVStore is only used in tmpop and we have a generic implementation.
</blockquote></details>

ok

---

*[elasticsearchstore/elasticsearchstore.go, line 141 at r2](https://beta.reviewable.io/reviews/stratumn/go-indigocore/357#-L6zn0pTc1XPiHO7JXYr:-L7-6oty1e6v-PGrrxRH:b2ni9b4) ([raw file](https://github.com/stratumn/go-indigocore/blob/af39fddd2241f38838a04dc602ac4a9884e099d7/elasticsearchstore/elasticsearchstore.go#L141)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

eventChans is not concurrent protected. It is the case for all stores...
`AddStoreEventChannel` is only called at storehttp startup, there is no race condition but we have to keep it in mind for later (check trace usage)

</blockquote></details>

ok!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/357)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-:-L7-BJXabsS804nlQ72p:bnfp4nl)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/357#-:-L70Cbw6I3-MLdHJEVDI:bnfp4nl)*

**Pull request merged**
