### PR TITLE
*: rename repository to go-indigocore

### PR DESCRIPTION
**Pull request by such**
The build will obviously be failing as long as I've not renamed the repository...

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/340)

### CODE REVIEW

**Comment by stephan83** [comment]
I think that go-indigocore is more standard for Go projects.

```go
import "go-indigocore"

indigocore.DoStuff()
```

vs

```go
import "indigocore-go"

go.DoStuff()
```

---

Review status: 0 of 178 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/340#-:-L4pmY32GJS65kBLCCZ5:b9f3hcu)*

**Comment by t-bast** [comment]
Since it is quite a calm period for indigo-core I think it would be a good idea to check this in soon, just need to sync with Alexandre and Simon who are working on it to make sure they don't have a lot of work that will be hard to migrate?

---

Review status: 0 of 178 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/340#-:-L59HATwY26YjjOQd4Cc:b-32tf0o)*

**Comment by such** [comment]
It's really not hard to migrate (basically just a search/replace)
@simonvadee, @alexppxela if you guys are ok I can merge this!

---

Review status: 0 of 178 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/sdk/340#-:-L59KAtY7O-y60dmhGhF:bkeqew5)*

**Comment by alexppxela** [comment]
I do not like prefixing project name by techno due to a language feature. But it is ok for me.
:lgtm: 

---

Reviewed 5 of 178 files at r1.
Review status: 5 of 178 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/340#-:-L59JlROg62m8kVz7F5f:boq97gi)*

**Comment by such** [comment]
Not a big fan either but let's say it's a convention rather than a feature! ;)

---

Review status: 5 of 178 files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/sdk/340#-:-L59LNMZAVt-7O6hRHHf:b-gv7zi4)*

**Pull request merged**
