### PR TITLE
btc: get bitcoin network ID from WIF

### PR DESCRIPTION
**Pull request by simonvadee**
I refactored this to use it in alice

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/410)

### CODE REVIEW

**Comment by t-bast** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[blockchain/btc/btc.go, line 38 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/410#-LAxQJNWE-UbksM1ptS3:-LAxQJNWE-UbksM1ptS4:boyl9ut) ([raw file](https://github.com/stratumn/go-indigocore/blob/36baf1bd30bd2b21605bd6fbbd85ae415de6e059/blockchain/btc/btc.go#L38)):*
> ```Go
> var (
> 	// ErrUnknwonBitcoinNetwork is returned when the network ID associated to the WIF is unknown.
> 	ErrUnknwonBitcoinNetwork = errors.New("WIF encoded private key uses unknown Bitcoin network")
> ```

nit: typo (Unknown)

---

*[blockchain/btc/btc.go, line 48 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/410#-LAxQan03SOCrotGDddx:-LAxQan03SOCrotGDddy:bciz9xc) ([raw file](https://github.com/stratumn/go-indigocore/blob/36baf1bd30bd2b21605bd6fbbd85ae415de6e059/blockchain/btc/btc.go#L48)):*
> ```Go
> 	WIF, err := btcutil.DecodeWIF(key)
> 	if err != nil {
> 		return "", errors.Wrapf(err, ErrBadWIF.Error())
> ```

nit: why Wrapf instead of Wrap?

---

*[blockchain/btc/btc_test.go, line 63 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/410#-LAxQmrW6oM8QSOop97-:-LAxQmrW6oM8QSOop970:bt4abp8) ([raw file](https://github.com/stratumn/go-indigocore/blob/36baf1bd30bd2b21605bd6fbbd85ae415de6e059/blockchain/btc/btc_test.go#L63)):*
> ```Go
> 			net, err := btc.GetNetworkFromWIF(tt.wif)
> 			if tt.err == "" {
> 				assert.Equal(t, net, tt.expectedNetwork)
> ```

nit: you could also assert.NoError in this if branch

---


*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/410)*

**Comment by alexppxela** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/410)*

**Comment by simonvadee** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[blockchain/btc/btc.go, line 38 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/410#-LAxQJNWE-UbksM1ptS3:-LAxRSv1Cw5XyHnnlQRJ:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/36baf1bd30bd2b21605bd6fbbd85ae415de6e059/blockchain/btc/btc.go#L38)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: typo (Unknown)
</blockquote></details>

Done.

---

*[blockchain/btc/btc.go, line 48 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/410#-LAxQan03SOCrotGDddx:-LAxRVbzA9nGr-kSSns3:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/36baf1bd30bd2b21605bd6fbbd85ae415de6e059/blockchain/btc/btc.go#L48)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: why Wrapf instead of Wrap?
</blockquote></details>

Done.

---

*[blockchain/btc/btc_test.go, line 63 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/410#-LAxQmrW6oM8QSOop97-:-LAxRaDbAGtK1lr7qzWH:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/36baf1bd30bd2b21605bd6fbbd85ae415de6e059/blockchain/btc/btc_test.go#L63)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: you could also assert.NoError in this if branch
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/410)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/410#-:-LAxRseQA9zVYFQUHtwP:bnfp4nl)*

**Comment by such** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

*[blockchain/btc/btc_test.go, line 49 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/410#-LAxSJtzAeK2HrR8hJev:-LAxSJu-93qtJSJO_qxU:b-g9dxab) ([raw file](https://github.com/stratumn/go-indigocore/blob/36baf1bd30bd2b21605bd6fbbd85ae415de6e059/blockchain/btc/btc_test.go#L49)):*
> ```Go
> 			wif:             "fakeWIF",
> 			err:             errors.Wrap(btcutil.ErrMalformedPrivateKey, btc.ErrBadWIF.Error()).Error(),
> 			expectedNetwork: btc.NetworkTest3,
> ```

not really thou

---

*[blockchain/btc/btc_test.go, line 55 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/410#-LAxSOQP49jRoF7yyBV2:-LAxSOQP49jRoF7yyBV3:b-blht00) ([raw file](https://github.com/stratumn/go-indigocore/blob/36baf1bd30bd2b21605bd6fbbd85ae415de6e059/blockchain/btc/btc_test.go#L55)):*
> ```Go
> 			wif:             "5KrPNVvAhnRBNMYRJUq58YMfyUMyVMQrQhhfFtcbT9rK67poC3F",
> 			err:             btc.ErrUnknwonBitcoinNetwork.Error(),
> 			expectedNetwork: btc.NetworkTest3,
> ```

not really neither

---


*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/410)*

**Comment by t-bast** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/410)*

**Comment by simonvadee** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[blockchain/btc/btc_test.go, line 49 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/410#-LAxSJtzAeK2HrR8hJev:-LAxU19VBoqfn8aA8goF:brm703f) ([raw file](https://github.com/stratumn/go-indigocore/blob/36baf1bd30bd2b21605bd6fbbd85ae415de6e059/blockchain/btc/btc_test.go#L49)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

not really thou
</blockquote></details>

:tired_face: 

---

*[blockchain/btc/btc_test.go, line 55 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/410#-LAxSOQP49jRoF7yyBV2:-LAxUF9B8K4rdmc5cJCo:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/36baf1bd30bd2b21605bd6fbbd85ae415de6e059/blockchain/btc/btc_test.go#L55)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

not really neither
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/410)*

**Comment by such** [comment]
*[blockchain/btc/btc_test.go, line 55 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/410#-LAxSOQP49jRoF7yyBV2:-LAxUKPFATIwlkBJh8E9:b-k73z76) ([raw file](https://github.com/stratumn/go-indigocore/blob/36baf1bd30bd2b21605bd6fbbd85ae415de6e059/blockchain/btc/btc_test.go#L55)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thanks

---


*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/410)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/410#-:-LAxUMZx9jQrVbtpwkRO:bnfp4nl)*

**Pull request merged**
