### PR TITLE
validator: reformat configuration

### PR DESCRIPTION
**Pull request by simonvadee**
- new validation configuration format
```json
{
	"testProcess": {
	  "pki": {
	    "alice.vandenbudenmayer@stratumn.com": {
	      "keys": ["TESTKEY1"],
	      "roles": ["employee"]
	    }
	  },
	  "types": {
	    "init": {
	      "signature": null,
	      "schema": {
		"type": "object",
		"properties": {
		  "string": {
		    "type": "string"
		  }
		}
	      }
	    },
	    "action": {
	      "signatures": ["it"]
	    }
	  }
	}
      }
```

- signatureValidator has been removed, signatures are now verified in `link.Validate` (`cs`package)
- `signature`package has been moved from `sdk/validator` to `sdk/cs`

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk/343)

### CODE REVIEW

**Comment by alexppxela** [comment]
Reviewed 23 of 27 files at r1.
Review status: 19 of 23 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cs/signature.go, line 52 at r1](https://reviewable.io:443/reviews/stratumn/sdk/343#-L597-TTWU99mB6wfX5k:-L597-TTWU99mB6wfX5l:bd4u0mc) ([raw file](https://github.com/stratumn/sdk/blob/be6e1d00d7c300738de48cc2c173124bf5d85467/cs/signature.go#L52)):*
> ```Go
> 	payload, err := jmespath.Search(s.Payload, l)
> 	if err != nil {
> 		return errors.Wrapf(err, "failed to execute JMESPATH query")
> ```

nit: `errors.Wrap(...)`

---

*[tmpop/tmpoptestcases/validation.go, line 41 at r1](https://reviewable.io:443/reviews/stratumn/sdk/343#-L597iPiqzVSampL_-kK:-L597iPiqzVSampL_-kL:b6x5q3z) ([raw file](https://github.com/stratumn/sdk/blob/be6e1d00d7c300738de48cc2c173124bf5d85467/tmpop/tmpoptestcases/validation.go#L41)):*
> ```Go
> 	      "signature": null,
> 	      "schema": {
> 		"type": "object",
> ```

nit: indentation

---

*[tmstore/testdata/rules.json, line 15 at r1](https://reviewable.io:443/reviews/stratumn/sdk/343#-L597xHwXZp4I3xdOQBn:-L597xHwXZp4I3xdOQBo:b3nlp2u) ([raw file](https://github.com/stratumn/sdk/blob/be6e1d00d7c300738de48cc2c173124bf5d85467/tmstore/testdata/rules.json#L15)):*
> ```JSON
>     "types": {
>       "init": {
>         "signature": null,
> ```

signature field is not mandatory?

---

*[validator/pki.go, line 56 at r1](https://reviewable.io:443/reviews/stratumn/sdk/343#-L598olilFG_8QCpMAU0:-L598olilFG_8QCpMAU1:bcegmz2) ([raw file](https://github.com/stratumn/sdk/blob/be6e1d00d7c300738de48cc2c173124bf5d85467/validator/pki.go#L56)):*
> ```Go
> 
> 	for _, key := range identity.Keys {
> 		if key == publicKey {
> ```

You've just checked that identity was found above.
This check loop is not necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/343)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 27 of 27 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[tmpop/tmpoptestcases/validation.go, line 39 at r1](https://reviewable.io:443/reviews/stratumn/sdk/343#-L59FSxpGaewifYS6i5g:-L59FSxqahA9Iv1Uu_XB:b-tc4nw) ([raw file](https://github.com/stratumn/sdk/blob/be6e1d00d7c300738de48cc2c173124bf5d85467/tmpop/tmpoptestcases/validation.go#L39)):*
> ```Go
> 	  "types": {
> 	    "init": {
> 	      "signature": null,
> ```

nit: shouldn't this be "signatures"? The end result will be the same (a nil signatures field), but it's better to be precise :)

---

*[validator/pki.go, line 56 at r1](https://reviewable.io:443/reviews/stratumn/sdk/343#-L598olilFG_8QCpMAU0:-L59GGNUB57LdTqx1wjL:bwnfxvs) ([raw file](https://github.com/stratumn/sdk/blob/be6e1d00d7c300738de48cc2c173124bf5d85467/validator/pki.go#L56)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

You've just checked that identity was found above.
This check loop is not necessary.
</blockquote></details>

Anyway you'll probably be changing that in another PR right? Since we said it would probably be better to use a structured object here instead of just a string (since a name and a role could collide if people are sneaky). But that's definitely for another PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/343#-:-L59G_YZWTwdnp3c84Ug:bnfp4nl)*

**Comment by simonvadee** [comment]
I forgot to add a couple of things in this PR, sorry for the trouble: 
- Multivalidator returns an error if a link does not match any validator
- `link.meta.action`is renamed `link.meta.type`

---

Review status: 10 of 26 files reviewed at latest revision, 5 unresolved discussions.

---

*[cs/signature.go, line 52 at r1](https://reviewable.io:443/reviews/stratumn/sdk/343#-L597-TTWU99mB6wfX5k:-L59CTjveaZL1mTGV9bX:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/be6e1d00d7c300738de48cc2c173124bf5d85467/cs/signature.go#L52)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

nit: `errors.Wrap(...)`
</blockquote></details>

Done.

---

*[tmpop/tmpoptestcases/validation.go, line 39 at r1](https://reviewable.io:443/reviews/stratumn/sdk/343#-L59FSxpGaewifYS6i5g:-L59QvJDn1OyfrJ22A1y:b-ww5dh) ([raw file](https://github.com/stratumn/sdk/blob/be6e1d00d7c300738de48cc2c173124bf5d85467/tmpop/tmpoptestcases/validation.go#L39)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: shouldn't this be "signatures"? The end result will be the same (a nil signatures field), but it's better to be precise :)
</blockquote></details>

you're right ! I removed that to be clearer.

---

*[tmpop/tmpoptestcases/validation.go, line 41 at r1](https://reviewable.io:443/reviews/stratumn/sdk/343#-L597iPiqzVSampL_-kK:-L59CzB_bCdae4CukjCn:b-896fix) ([raw file](https://github.com/stratumn/sdk/blob/be6e1d00d7c300738de48cc2c173124bf5d85467/tmpop/tmpoptestcases/validation.go#L41)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

nit: indentation
</blockquote></details>

Done.

---

*[tmstore/testdata/rules.json, line 15 at r1](https://reviewable.io:443/reviews/stratumn/sdk/343#-L597xHwXZp4I3xdOQBn:-L59CzdBlpBHMnqXoGps:b-nmamj8) ([raw file](https://github.com/stratumn/sdk/blob/be6e1d00d7c300738de48cc2c173124bf5d85467/tmstore/testdata/rules.json#L15)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

signature field is not mandatory?
</blockquote></details>

it's not, but it does not change anything. I removed it for clarity.

---

*[validator/pki.go, line 56 at r1](https://reviewable.io:443/reviews/stratumn/sdk/343#-L598olilFG_8QCpMAU0:-L59DNMqeP1_QWhh1C4q:b-7mbxe1) ([raw file](https://github.com/stratumn/sdk/blob/be6e1d00d7c300738de48cc2c173124bf5d85467/validator/pki.go#L56)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Anyway you'll probably be changing that in another PR right? Since we said it would probably be better to use a structured object here instead of just a string (since a name and a role could collide if people are sneaky). But that's definitely for another PR.
</blockquote></details>

yeah there was a big problem with this func after my update.. fixed it.
I'll take care of the structured identity in a next PR indeed!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/sdk/343#-:-L59ZaBD5-tmndlk32Wh:b1yhxgf)*

**Comment by alexppxela** [comment]
Reviewed 16 of 16 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/343)*

**Comment by alexppxela** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/343#-:-L59hErDF-VThlJmRTRU:bnfp4nl)*

**Comment by t-bast** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/343)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 4 of 16 files at r2, 16 of 16 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/343#-:-L59qREhgugn-b_L1hl-:bnfp4nl)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 16 of 16 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/343#-:-L59wiR3-rumdxElNljb:bnfp4nl)*

**Pull request merged**
