### PR TITLE
add search API on Elastic Search store

### PR DESCRIPTION
**Pull request by jeremie-stratumn**
- add SimpleSearchQuery
- add MultiMatchQuery (not very useful I think..)
- add specific tests
- add debug logging feature
- handle connection error correctly

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/369)

### CODE REVIEW

**Comment by alexppxela** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[elasticsearchstore/api.go, line 150 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_6xch4imhu1eg9xHS:-L7_6xch4imhu1eg9xHT:btb64y9) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/api.go#L150)):*
> ```Go
> }
> 
> // SearchQuery contains paghination and query string information.
> ```

typo: _paghination_

---

*[elasticsearchstore/cmd.go, line 78 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_0YgsDHyFVdzXaC8f:-L7_0YgtMap0XWe2akYb:btiobta) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/cmd.go#L78)):*
> ```Go
> 	flag.BoolVar(&sniffing, "sniffing", false, "turn on elastic search nodes sniffing")
> 	flag.BoolVar(&drop, "drop", false, "drop indexes then exit")
> 	flag.BoolVar(&debug, "debug", false, "use debug log level")
> ```

I prefer option like `--log-level=[debug info error]`. It is more configurable.

---

*[elasticsearchstore/elasticsearchstore_test.go, line 120 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_2WWR59GSkWah6u9n:-L7_2WWR59GSkWah6u9o:b-nnu98) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/elasticsearchstore_test.go#L120)):*
> ```Go
> func verifyResultsCount(t *testing.T, err error, slice cs.SegmentSlice, expectedCount int) {
> 	assert.NoError(t, err)
> 	assert.NotNil(t, slice)
> ```

It is not necessary to checkk nil slice, len will return 0 if slice is nil

---

*[elasticsearchstore/elasticsearchstore_test.go, line 121 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_38v3l4X179WtBlK0:-L7_38v3l4X179WtBlK1:by14lwq) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/elasticsearchstore_test.go#L121)):*
> ```Go
> 	assert.NoError(t, err)
> 	assert.NotNil(t, slice)
> 	require.Equal(t, expectedCount, len(slice), "Invalid number of results")
> ```

`require.Len(t, slice, expectedCount, "Invalid number of results")`

---

*[elasticsearchstore/elasticsearchstore_test.go, line 123 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_21kurUCPFzfyglb2:-L7_21kurUCPFzfyglb3:b-mrj3mw) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/elasticsearchstore_test.go#L123)):*
> ```Go
> 	require.Equal(t, expectedCount, len(slice), "Invalid number of results")
> }
> func TestElasticSearchStoreSearch(t *testing.T) {
> ```

empty line between functions for linter

---

*[elasticsearchstore/elasticsearchstore_test.go, line 163 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_5D2lkv6lBFNk9MJB:-L7_5D2lkv6lBFNk9MJC:b-mdgunv) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/elasticsearchstore_test.go#L163)):*
> ```Go
> 			})
> 			verifyResultsCount(t, err, slice, 1)
> 			hash, _ := link1.HashString()
> ```

You can save hash1 and hash2 in the init phase to DRY in each subtests

---

*[elasticsearchstore/elasticsearchstore_test.go, line 164 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_3s9tBJH691LZHBuw:-L7_3s9uxNTha61a2d_Q:b-t6kpj6) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/elasticsearchstore_test.go#L164)):*
> ```Go
> 			verifyResultsCount(t, err, slice, 1)
> 			hash, _ := link1.HashString()
> 			assert.Equal(t, slice[0].GetLinkHashString(), hash, "Wrong link was found")
> ```

nit: second argument of `Equal` should be the expected value (it is the same for all testify functions except `Len`...)

---

*[elasticsearchstore/elasticsearchstore_test.go, line 270 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_6mz6EN1zJi4HiCwA:-L7_6mz6EN1zJi4HiCwB:b-aob1lv) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/elasticsearchstore_test.go#L270)):*
> ```Go
> 		assert.Equal(t, len(expectedTokens), len(doc.StateTokens), "Invalid number of tokens")
> 		for _, token := range expectedTokens {
> 			assert.Contains(t, doc.StateTokens, token, "Invalid tokens exracted")
> ```

typo: _exracted_

---

*[elasticsearchstore/elasticsearchstore_test.go, line 278 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_1RXrx5cg81XVjX7G:-L7_1RXrx5cg81XVjX7H:bmajxtx) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/elasticsearchstore_test.go#L278)):*
> ```Go
> 	config := &Config{
> 		URL:   fmt.Sprintf("http://%s:%s", domain, port),
> 		Debug: false,
> ```

nit: default value in go is `nil,0,false,[],""`. It is not necessary to specify Debug

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/369)*

**Comment by alexppxela** [comment]
You have to rebase master to fix semaphore tests

---

Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-:-L7_8amOZpRmoGq_HBGM:b-6htl12)*

**Comment by jeremie-stratumn** [comment]
thanks!

---

Review status: 0 of 4 files reviewed at latest revision, 10 unresolved discussions.

---

*[elasticsearchstore/api.go, line 150 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_6xch4imhu1eg9xHS:-L7_CvZ7bd0aeh7JzrGi:bb7s9xe) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/api.go#L150)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

typo: _paghination_
</blockquote></details>

yep!

---

*[elasticsearchstore/cmd.go, line 78 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_0YgsDHyFVdzXaC8f:-L7_HuGhM4X8_TU4QP5-:bb7f2mf) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/cmd.go#L78)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

I prefer option like `--log-level=[debug info error]`. It is more configurable.
</blockquote></details>

done

---

*[elasticsearchstore/elasticsearchstore_test.go, line 120 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_2WWR59GSkWah6u9n:-L7_D1DKbcmwIEWUjUaL:b-q8ilnv) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/elasticsearchstore_test.go#L120)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

It is not necessary to checkk nil slice, len will return 0 if slice is nil
</blockquote></details>

gotcha

---

*[elasticsearchstore/elasticsearchstore_test.go, line 121 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_38v3l4X179WtBlK0:-L7_DIDCkVuFAMGn8g9B:bb7f2mf) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/elasticsearchstore_test.go#L121)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

`require.Len(t, slice, expectedCount, "Invalid number of results")`
</blockquote></details>

done

---

*[elasticsearchstore/elasticsearchstore_test.go, line 123 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_21kurUCPFzfyglb2:-L7_DNThg2Yu-tqzt2y2:bb7f2mf) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/elasticsearchstore_test.go#L123)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

empty line between functions for linter
</blockquote></details>

done

---

*[elasticsearchstore/elasticsearchstore_test.go, line 163 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_5D2lkv6lBFNk9MJB:-L7_DOJNqlq0S_vXNuTB:b-pb9bue) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/elasticsearchstore_test.go#L163)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

You can save hash1 and hash2 in the init phase to DRY in each subtests
</blockquote></details>

indeed

---

*[elasticsearchstore/elasticsearchstore_test.go, line 164 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_3s9tBJH691LZHBuw:-L7_EBHrFJbz5OTZZZCp:bb7f2mf) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/elasticsearchstore_test.go#L164)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

nit: second argument of `Equal` should be the expected value (it is the same for all testify functions except `Len`...)
</blockquote></details>

done

---

*[elasticsearchstore/elasticsearchstore_test.go, line 270 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_6mz6EN1zJi4HiCwA:-L7_EI8M_K1NdvnpIKyq:bb7f2mf) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/elasticsearchstore_test.go#L270)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

typo: _exracted_
</blockquote></details>

done

---

*[elasticsearchstore/elasticsearchstore_test.go, line 278 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_1RXrx5cg81XVjX7G:-L7_ELp7jnyN7qZa7-Fe:b97qngo) ([raw file](https://github.com/stratumn/go-indigocore/blob/3c4b68bc04c8428bd59832b21fde0675f57a2e16/elasticsearchstore/elasticsearchstore_test.go#L278)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

nit: default value in go is `nil,0,false,[],""`. It is not necessary to specify Debug
</blockquote></details>

done. I didnt define it for that purpose, it was just for easily turn on debug for tests..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-:-L7_I4SUham3XNabbfNB:bd5l6mr)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[elasticsearchstore/elasticsearchstore_test.go, line 221 at r2](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_JbXyor4fh6e7C18B:-L7_JbXzTfQw5sy4ozXw:bj02phc) ([raw file](https://github.com/stratumn/go-indigocore/blob/5650ef395b6180ca33e1772695e96e458c8f6018/elasticsearchstore/elasticsearchstore_test.go#L221)):*
> ```Go
> 			verifyResultsCount(t, err, slice, 2)
> 			assert.Contains(t, []string{hash1, hash2}, slice[0].GetLinkHashString(), "Wrong link was found")
> 			assert.Contains(t, []string{hash1, hash2}, slice[1].GetLinkHashString(), "Wrong link was found")
> ```

To be sure that result is ok, you should check if `slice[0].GetLinkHashString()` is different of `slice[1].GetLinkHashString()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-:-L7_K1IAGsM_mH-nsftp:bnfp4nl)*

**Comment by jeremie-stratumn** [comment]
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[elasticsearchstore/elasticsearchstore_test.go, line 221 at r2](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-L7_JbXyor4fh6e7C18B:-L7_KkH27XaEgHbKypCn:bb7pcsz) ([raw file](https://github.com/stratumn/go-indigocore/blob/5650ef395b6180ca33e1772695e96e458c8f6018/elasticsearchstore/elasticsearchstore_test.go#L221)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

To be sure that result is ok, you should check if `slice[0].GetLinkHashString()` is different of `slice[1].GetLinkHashString()`
</blockquote></details>

true

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/369)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/369#-:-L7_OJo5OzhMhgNFgRUn:bnfp4nl)*

**Pull request merged**
