### PR TITLE
logging: add opencensus

### PR DESCRIPTION
**Pull request by t-bast**
Yes, this PR looks huge, but do not fear: most of it is simply adding a context parameter to methods that should be instrumented.
The only files that you should really review (it will help understand how metrics work) are:

- cmd/tmstore/main.go
- jsonhttp/jsonhttp.go
- monitoring/errorcode.go
- store/store.go
- store/storehttp/cmd.go
- store/storehttp/metrics.go
- store/storehttp/storehttp.go
- tmpop/metrics.go and the tmpop files
-  tmstore/tmstore.go

I'll add instrumentation on each specific store in other PRs.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/372)

### CODE REVIEW

**Comment by alexppxela** [comment]
Reviewed 15 of 68 files at r1.
Review status: 15 of 68 files reviewed at latest revision, all discussions resolved.

---

*[store/storehttp/metrics.go, line 39 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372#-L8XI4RNCGYZfadst9c7:-L8XI4RNCGYZfadst9c8:b-l76ns7) ([raw file](https://github.com/stratumn/go-indigocore/blob/d7cfa61721c81a7077449d081876b1191ec4450d/store/storehttp/metrics.go#L39)):*
> ```Go
> // exposeMetrics configures metrics and traces exporters and
> // exposes them to collectors.
> func (s *Server) exposeMetrics() {
> ```

It might take the `Config` to allow more configuration for period & jaeger endpoint

---

*[tmpop/metrics.go, line 117 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372#-L8XL33J4Y0yN9Zbu-Sg:-L8XL33J4Y0yN9Zbu-Sh:b-jbf0zm) ([raw file](https://github.com/stratumn/go-indigocore/blob/d7cfa61721c81a7077449d081876b1191ec4450d/tmpop/metrics.go#L117)):*
> ```Go
> 	log.Infof("Exposing metrics on :5001")
> 	http.Handle("/metrics", metricsExporter)
> 	http.ListenAndServe(":5001", nil)
> ```

Might be configurable like 5000 for storehttp

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372)*

**Comment by t-bast** [comment]
Review status: 15 of 68 files reviewed at latest revision, 2 unresolved discussions.

---

*[store/storehttp/metrics.go, line 39 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372#-L8XI4RNCGYZfadst9c7:-L8XLWgz6gpF8fkb4c35:b-sb2tpy) ([raw file](https://github.com/stratumn/go-indigocore/blob/d7cfa61721c81a7077449d081876b1191ec4450d/store/storehttp/metrics.go#L39)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

It might take the `Config` to allow more configuration for period & jaeger endpoint
</blockquote></details>

Yes, that's in my todo list for a later PR ;)

---

*[tmpop/metrics.go, line 117 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372#-L8XL33J4Y0yN9Zbu-Sg:-L8XLfV_63_7fnhx65Ae:bghf9aw) ([raw file](https://github.com/stratumn/go-indigocore/blob/d7cfa61721c81a7077449d081876b1191ec4450d/tmpop/metrics.go#L117)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Might be configurable like 5000 for storehttp
</blockquote></details>

Same, in my todo list for another PR ;)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372)*

**Comment by alexppxela** [comment]
Reviewed 9 of 68 files at r1.
Review status: 24 of 68 files reviewed at latest revision, 2 unresolved discussions.

---

*[store/storetestcases/batch.go, line 46 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372#-L8XLpP37E14_1EGfpzg:-L8XLpP37E14_1EGfpzh:b2qy7ro) ([raw file](https://github.com/stratumn/go-indigocore/blob/d7cfa61721c81a7077449d081876b1191ec4450d/store/storetestcases/batch.go#L46)):*
> ```Go
> 		link := cstesting.RandomLink()
> 		link.Meta.MapID = fmt.Sprintf("map%d", i%3)
> 		a.CreateLink(ctx, link)
> ```

nit: Maybe using context.TODO() could be sufficient. (This remark is for everywhere)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372)*

**Comment by t-bast** [comment]
Review status: 24 of 68 files reviewed at latest revision, 3 unresolved discussions.

---

*[store/storetestcases/batch.go, line 46 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372#-L8XLpP37E14_1EGfpzg:-L8XMcGSBKiGiEQhBZP3:b-adae23) ([raw file](https://github.com/stratumn/go-indigocore/blob/d7cfa61721c81a7077449d081876b1191ec4450d/store/storetestcases/batch.go#L46)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

nit: Maybe using context.TODO() could be sufficient. (This remark is for everywhere)
</blockquote></details>

I don't know, there is no TODO per se. context.Background() is fine for this benchmark (and for tests), there isn't anything to change don't you think?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372)*

**Comment by alexppxela** [comment]
Reviewed 32 of 68 files at r1.
Review status: 56 of 68 files reviewed at latest revision, 3 unresolved discussions.

---

*[Gopkg.toml, line 98 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372#-L8XNQl5969AOD0mDSLs:-L8XNQl5969AOD0mDSLt:b-rdfmg2) ([raw file](https://github.com/stratumn/go-indigocore/blob/d7cfa61721c81a7077449d081876b1191ec4450d/Gopkg.toml#L98)):*
> ```TOML
> [[constraint]]
>   name = "go.opencensus.io"
>   version = "0.6.0"
> ```

By default `dep` uses the latest version.

---

*[store/storetesting/mockadapter.go, line 164 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372#-L8XMUHVEJDsV9dv85Sd:-L8XMUHVEJDsV9dv85Se:b-8fx2u7) ([raw file](https://github.com/stratumn/go-indigocore/blob/9a194f683f7e6ef1cc4ab2da682a50c224102143/store/storetesting/mockadapter.go#L164)):*
> ```Go
> 	// An optional implementation of the function.
> 	Fn func(*types.Bytes32) (*cs.Segment, error)
> }
> ```

:+1: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372)*

**Comment by alexppxela** [comment]
Review status: 56 of 68 files reviewed at latest revision, 3 unresolved discussions.

---

*[store/storehttp/metrics.go, line 39 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372#-L8XI4RNCGYZfadst9c7:-L8XNh8-AhkoTMm1lZ0O:b-7m74ox) ([raw file](https://github.com/stratumn/go-indigocore/blob/d7cfa61721c81a7077449d081876b1191ec4450d/store/storehttp/metrics.go#L39)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Yes, that's in my todo list for a later PR ;)
</blockquote></details>

nice!

---

*[store/storetestcases/batch.go, line 46 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372#-L8XLpP37E14_1EGfpzg:-L8XOxJ7BQdQV76fgxQ1:b-n7hs2r) ([raw file](https://github.com/stratumn/go-indigocore/blob/d7cfa61721c81a7077449d081876b1191ec4450d/store/storetestcases/batch.go#L46)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

I don't know, there is no TODO per se. context.Background() is fine for this benchmark (and for tests), there isn't anything to change don't you think?
</blockquote></details>

As discussed, I did not understood the meaning of context.TODO. It is not necessary to modify is later. Background is good.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372)*

**Comment by t-bast** [comment]
Review status: 56 of 68 files reviewed at latest revision, 1 unresolved discussion.

---

*[Gopkg.toml, line 98 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/372#-L8XNQl5969AOD0mDSLs:-L8XR0xz1XR5-imI5LtH:b-mwukim) ([raw file](https://github.com/stratumn/go-indigocore/blob/d7cfa61721c81a7077449d081876b1191ec4450d/Gopkg.toml#L98)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

By default `dep` uses the latest version.
</blockquote></details>

Indeed I was trying to fix the dependency issue with thrift, this is not needed anymore. Removing it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/372)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 12 of 68 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[dummystore/dummystore.go, line 92 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372#-L8XR4LN6mdU5MweN0O-:-L8XPeNZ1ZpMxCjyN3td:b-fdkglw) ([raw file](https://github.com/stratumn/go-indigocore/blob/d7cfa61721c81a7077449d081876b1191ec4450d/dummystore/dummystore.go#L92)):*
> ```Go
> // GetInfo implements github.com/stratumn/go-indigocore/store.Adapter.GetInfo.
> func (a *DummyStore) GetInfo(ctx context.Context) (interface{}, error) {
> 	_, span := trace.StartSpan(ctx, "dummystore/GetInfo")
> ```

As discussed, Google advices to put the complete path to the method and do not factorize as _store/GetInfo_

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372#-:-L8XRq5eEFE8A6cMhzAt:bnfp4nl)*

**Comment by such** [comment]
Reviewed 66 of 68 files at r1, 2 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[tmpop/tmpop.go, line 169 at r2](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372#-L8YIAEu0CbafKmG_LXp:-L8YIAEu0CbafKmG_LXq:bqgqdvs) ([raw file](https://github.com/stratumn/go-indigocore/blob/29db9a741242810f4d0e9a657d2ce4921a41999a/tmpop/tmpop.go#L169)):*
> ```Go
> 	t.currentHeader = &req.Header
> 	if t.currentHeader == nil {
> 		log.Error("Cannot begin block without header")
> ```

are we getting rid of the logs once we're confortable with traces or do we consider they serve a different purpose?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tmpop/tmpop.go, line 169 at r2](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372#-L8YIAEu0CbafKmG_LXp:-L8aJEED30iQXwsvYMwU:b9isq2e) ([raw file](https://github.com/stratumn/go-indigocore/blob/29db9a741242810f4d0e9a657d2ce4921a41999a/tmpop/tmpop.go#L169)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

are we getting rid of the logs once we're confortable with traces or do we consider they serve a different purpose?
</blockquote></details>

I'm not sure yet, what do you think? I think those logs are still useful when running locally because it's easy to read them as they flow...
Uber does tracing + logs to stdout (they use golang's "zap" library to write structured logs).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372)*

**Comment by such** [comment]
*[tmpop/tmpop.go, line 169 at r2](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372#-L8YIAEu0CbafKmG_LXp:-L8aZ-FVDUGqSSWuEiY9:b-86tkzg) ([raw file](https://github.com/stratumn/go-indigocore/blob/29db9a741242810f4d0e9a657d2ce4921a41999a/tmpop/tmpop.go#L169)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

I'm not sure yet, what do you think? I think those logs are still useful when running locally because it's easy to read them as they flow...
Uber does tracing + logs to stdout (they use golang's "zap" library to write structured logs).
</blockquote></details>

I can see how logs can be useful. We could maybe figure out a way to export the tracing to stdout when running locally though

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/372)*

**Pull request merged**
