### PR TITLE
Type link meta

### LINKED ISSUE #332: cs: serialize link.meta
In order to avoid casts as much as we can, the `link.meta` should be serialized in a go object instead of `map[string]interface{}`. However, we should still have the ability to add custom fields (depending on the use-case for which the indigo sdk is used). 

```golang
type LinkMeta struct {
    MapID string
    Process string
    Action string
    Type string
    Inputs []string
    Refs []*Reference // we should also come up with a serialisation for references
    Tags []string
    PrevLinkHash string
    Data map[string]interface{} //customizable fields
}
```

Implementation of SRP X is a good occasion to make that change

### PR DESCRIPTION
**Pull request by alexppxela**
Resolves #332 

This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/352)

### CODE REVIEW

**Comment by alexppxela** [comment]
Review status: 0 of 37 files reviewed at latest revision, 3 unresolved discussions.

---

*[cs/cs.go, line 141 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wO0fFR3CkrG4xhlDJ:-L5wO0fFR3CkrG4xhlDK:bpp2dza) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L141)):*
> ```Go
> 	Inputs       []string               `json:"inputs"`
> 	Tags         []string               `json:"tags"`
> 	Priority     float64                `json:"priority,omitempty"`
> ```

Priority is now mandatory. If not set its value is `0` instead of `-inf`.
I think it is not a problem because user always set priority or never. Is it ok for you?

---

*[cs/cs.go, line 185 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wNH8o8nhzoOeou730:-L5wNH8prAgATmu_Yse_:berdy32) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L185)):*
> ```Go
> // It assumes the link is valid.
> func (l *Link) GetMapID() string {
> 	return l.Meta.MapID
> ```

I think it is better to remove all getter which do nothing. What do you think?

---

*[rethinkstore/rethinkstore.go, line 178 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wNcggx_61jBytuZbO:-L5wNcggx_61jBytuZbP:b-sc9df1) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/rethinkstore/rethinkstore.go#L178)):*
> ```Go
> 
> // Rethink cannot retrieve nil slices, so we force putting empty slices in Link
> func formatLink(link *cs.Link) *cs.Link {
> ```

Nil slices are stored as empty stores in rethink. So on retrieval, link has empty slices and linkHas is different than the original one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/352)*

**Comment by t-bast** [comment]
Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[agent/client/utils_test.go, line 61 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wggYudCsAiyVHeDhj:-L5wggYvreSz2-PjWZeG:ba3dfna) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/agent/client/utils_test.go#L61)):*
> ```Go
> 	var refs []cs.SegmentReference
> 	for refIdx, in := range inputSlice {
> 		// var ref client.SegmentRef
> ```

Remove?

---

*[cs/cs.go, line 139 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5whX1ThPahMeXxv7gz:-L5whX1ThPahMeXxv7h-:b-51voap) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L139)):*
> ```Go
> 	Action       string                 `json:"action"`
> 	Type         string                 `json:"type"`
> 	Inputs       []string               `json:"inputs"`
> ```

nit: should it really be []string and not []interface{}?

---

*[cs/cs.go, line 141 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wO0fFR3CkrG4xhlDJ:-L5whMlCMjXV7GlgZiS7:bl71opj) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L141)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Priority is now mandatory. If not set its value is `0` instead of `-inf`.
I think it is not a problem because user always set priority or never. Is it ok for you?
</blockquote></details>

It sounds good to me, but probably Adrien's input would be more important than mine on this.

---

*[cs/cs.go, line 185 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wNH8o8nhzoOeou730:-L5whkguCzSJjtiWSQ_p:bdzqdh) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L185)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

I think it is better to remove all getter which do nothing. What do you think?
</blockquote></details>

Definitely, it's good to clean it up and directly access the member instead. Except for getters that have a bit of logic like GetPrevLinkHash that converts to *types.Bytes32.

---

*[cs/cs.go, line 245 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wi61Hftowlv5STr4M:-L5wi61Hftowlv5STr4N:b-1tgubc) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L245)):*
> ```Go
> 	}
> 
> 	if v, ok := l.Meta.Data["priority"]; ok {
> ```

Shouldn't this be using l.Meta.Priority?

---

*[cs/util_test.go, line 45 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wiODZeygF8j9ggMlh:-L5wiODZeygF8j9ggMli:ba3dfna) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/util_test.go#L45)):*
> ```Go
> 
> func appendRefSegment(l, ref *cs.Link) {
> 	// var refs []interface{}
> ```

Remove?

---

*[cs/util_test.go, line 54 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wiPZncjHk9RF6w2Ch:-L5wiPZncjHk9RF6w2Ci:ba3dfna) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/util_test.go#L54)):*
> ```Go
> 
> func appendRefLink(l *cs.Link, process, linkHash string) {
> 	// var refs []interface{}
> ```

Remove?

---

*[rethinkstore/rethinkstore.go, line 178 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wjI6yX08vvs2x6Ekf:-L5wjI6yX08vvs2x6Ekg:bwit84b) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/rethinkstore/rethinkstore.go#L178)):*
> ```Go
> 
> // Rethink cannot retrieve nil slices, so we force putting empty slices in Link
> func formatLink(link *cs.Link) *cs.Link {
> ```

You probably don't need to return the link since you're modifying it in place.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/352)*

**Comment by simonvadee** [comment]
so satisfying to see all those casts go away... amazing thank's !

---

Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[agent/client/client.go, line 42 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wkAl9WKh7nsL_o-_f:-L5wkAl9WKh7nsL_o-_g:b2mweyt) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/agent/client/client.go#L42)):*
> ```Go
> 
> //SegmentRef defines a format for a valid reference.
> type SegmentRef struct {
> ```

can this be imported from `cs`?

---

*[cs/cs.go, line 139 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5whX1ThPahMeXxv7gz:-L5wkypYIhvUcQSjapp0:buvp18y) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L139)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: should it really be []string and not []interface{}?
</blockquote></details>

you may be right... (although it won't work when an input is an array) but I think it's a complicated question that we can answer later (UX-ly speaking, how would a user send custom objects ?)

---

*[cs/cs.go, line 141 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wO0fFR3CkrG4xhlDJ:-L5weOcZAzvNRHUjNavE:b9uw8gf) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L141)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

It sounds good to me, but probably Adrien's input would be more important than mine on this.
</blockquote></details>

It don't think it's a problem at all, `-inf` is not really different from 0 in this case since a user should never set a negative priority right ?

---

*[cs/cs.go, line 185 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wNH8o8nhzoOeou730:-L5wf80wdEzo8BNlORdZ:b-1ezear) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L185)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

I think it is better to remove all getter which do nothing. What do you think?
</blockquote></details>

agreed :+1:

---

*[cs/util_test.go, line 45 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wgfC6mh9vjp49aYzO:-L5wgfC6mh9vjp49aYzP:b-vm1gei) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/util_test.go#L45)):*
> ```Go
> 
> func appendRefSegment(l, ref *cs.Link) {
> 	// var refs []interface{}
> ```

commented code (same below)

---

*[rethinkstore/main_test.go, line 50 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5whElH88QRBv-xFYk-:-L5whElH88QRBv-xFYk0:b-91pxvn) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/rethinkstore/main_test.go#L50)):*
> ```Go
> 	containerName := "indigo_rethinkstore_test"
> 	p, _ := nat.NewPort("tcp", port)
> 	pa, _ := nat.NewPort("tcp", adminPort)
> ```

why is this needed ?

---

*[rethinkstore/rethinkstore.go, line 171 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5whkgPSAcb_aLpHtj2:-L5whkgPSAcb_aLpHtj3:b-hmm8j1) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/rethinkstore/rethinkstore.go#L171)):*
> ```Go
> }
> 
> func avoidNilStringSlices(s *[]string) {
> ```

nit: not sure we need a dedicated function for that, but never mind

---

*[rethinkstore/rethinkstore.go, line 178 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wjI6yX08vvs2x6Ekf:-L5wlm-yNGA-yTTdTldR:b-m93yse) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/rethinkstore/rethinkstore.go#L178)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

You probably don't need to return the link since you're modifying it in place.
</blockquote></details>

the return value is used in `BufferedBatch`

---

*[rethinkstore/rethinkstore.go, line 194 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wi593VW0YjKuYD032:-L5wi593VW0YjKuYD033:b6b51g2) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/rethinkstore/rethinkstore.go#L194)):*
> ```Go
> 	prevLinkHash := link.GetPrevLinkHash()
> 
> 	formatLink(link)
> ```

passing pointers around and updating the values is not really idiomatic in go, I'd rather use the return value.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-:-L5wja0l9ZvNzUQM7Xgw:b-pgsdzq)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[cs/cs.go, line 139 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5whX1ThPahMeXxv7gz:-L5wmZV-8Nn6mcfwt-DR:b-145s3e) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L139)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

you may be right... (although it won't work when an input is an array) but I think it's a complicated question that we can answer later (UX-ly speaking, how would a user send custom objects ?)
</blockquote></details>

Jeremie was talking about this, and ways to provide type annotations or a schema in the UI, and then the agent could cast a few types (for example string, int, float, bool to begin with, no need for complex types it would already be very helpful to have support for those simple types).
But I agree that it can be for later :).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/352)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 14 unresolved discussions.

---

*[agent/client/client.go, line 42 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wkAl9WKh7nsL_o-_f:-L5wquS4G7kI08SHyqZ5:b-ek1qyl) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/agent/client/client.go#L42)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

can this be imported from `cs`?
</blockquote></details>

Why not, I'll try

---

*[agent/client/utils_test.go, line 61 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wggYudCsAiyVHeDhj:-L5wlF7IlFAEAF2TnYSa:bb7m3jc) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/agent/client/utils_test.go#L61)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

oops

---

*[cs/cs.go, line 139 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5whX1ThPahMeXxv7gz:-L5woxue7kuoTWlwKN1m:b-gr7muf) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L139)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Jeremie was talking about this, and ways to provide type annotations or a schema in the UI, and then the agent could cast a few types (for example string, int, float, bool to begin with, no need for complex types it would already be very helpful to have support for those simple types).
But I agree that it can be for later :).
</blockquote></details>

I can put `[]interface{}` to manage simple types and we can enhance it later

---

*[cs/cs.go, line 141 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wO0fFR3CkrG4xhlDJ:-L5wm5njiMVH3XBKXfX8:b-ejvp9z) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L141)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

It don't think it's a problem at all, `-inf` is not really different from 0 in this case since a user should never set a negative priority right ?
</blockquote></details>

negative values are allowed (cf. tests)

---

*[cs/cs.go, line 245 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wi61Hftowlv5STr4M:-L5wmImsiUGOMY4D6SRZ:b-uncjdc) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L245)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Shouldn't this be using l.Meta.Priority?
</blockquote></details>

I didn't put `Priority` at the beginning to keep it optional. And I forgot removing the test.
Done.

---

*[cs/util_test.go, line 45 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wiODZeygF8j9ggMlh:-L5wmkmMppETrTGhuVCD:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/util_test.go#L45)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.

---

*[cs/util_test.go, line 45 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wgfC6mh9vjp49aYzO:-L5wml78K0VvCTRPgC5B:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/util_test.go#L45)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

commented code (same below)
</blockquote></details>

Done.

---

*[cs/util_test.go, line 54 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wiPZncjHk9RF6w2Ch:-L5wmlffNLwxdvj0FP1D:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/util_test.go#L54)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Remove?
</blockquote></details>

Done.

---

*[rethinkstore/main_test.go, line 50 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5whElH88QRBv-xFYk-:-L5wmpXvNnGpkcVd9Sp3:b-al41dn) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/rethinkstore/main_test.go#L50)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

why is this needed ?
</blockquote></details>

To debug tests. 8080 is too standard, I can change it.
18080?

---

*[rethinkstore/rethinkstore.go, line 171 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5whkgPSAcb_aLpHtj2:-L5wnf8NY_eo8NGzl_0a:bne6wjd) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/rethinkstore/rethinkstore.go#L171)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

nit: not sure we need a dedicated function for that, but never mind
</blockquote></details>

With generics, it could be great. But for 2 calls, I can repeat it.

---

*[rethinkstore/rethinkstore.go, line 178 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wjI6yX08vvs2x6Ekf:-L5wnKzaIdiDSwK6CEwm:b-pns81x) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/rethinkstore/rethinkstore.go#L178)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

the return value is used in `BufferedBatch`
</blockquote></details>

Yes I return it to simplify rethinkBufferedBatch.CreateLink write

---

*[rethinkstore/rethinkstore.go, line 194 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wi593VW0YjKuYD032:-L5wr2W54rLGA6HAZopp:b-1oq786) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/rethinkstore/rethinkstore.go#L194)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

passing pointers around and updating the values is not really idiomatic in go, I'd rather use the return value.
</blockquote></details>

To do not be confusing, I'll change the function to do not return value (as said @t-bast ).
I prefer changing the signature than be clean and make a deep copy of the link and affect it to `link` btw.
Are you ok, with that?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/352)*

**Comment by simonvadee** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[rethinkstore/main_test.go, line 50 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5whElH88QRBv-xFYk-:-L5wtomzCsTdgnC1Qs9t:b3ofbbh) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/rethinkstore/main_test.go#L50)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

To debug tests. 8080 is too standard, I can change it.
18080?

</blockquote></details>

I didn't understand why 28015 wasn't enough, but 8080 is fine

---

*[rethinkstore/rethinkstore.go, line 194 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wi593VW0YjKuYD032:-L5wtTZ29W2qb8fQXl_j:b-hv9eb7) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/rethinkstore/rethinkstore.go#L194)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

To do not be confusing, I'll change the function to do not return value (as said @t-bast ).
I prefer changing the signature than be clean and make a deep copy of the link and affect it to `link` btw.
Are you ok, with that?
</blockquote></details>

yes :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/352)*

**Comment by alexppxela** [comment]
Review status: 28 of 37 files reviewed at latest revision, 11 unresolved discussions.

---

*[rethinkstore/main_test.go, line 50 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5whElH88QRBv-xFYk-:-L5x34p25SGhWJu3P3tq:boup4dd) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/rethinkstore/main_test.go#L50)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

I didn't understand why 28015 wasn't enough, but 8080 is fine
</blockquote></details>

I've put 18080 to avoid unit test failure if port 8080 is already used

---

*[rethinkstore/rethinkstore.go, line 178 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wjI6yX08vvs2x6Ekf:-L5x31dmZFmbEyiceb1v:b499q7j) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/rethinkstore/rethinkstore.go#L178)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Yes I return it to simplify rethinkBufferedBatch.CreateLink write
</blockquote></details>

Changed

---

*[rethinkstore/rethinkstore.go, line 194 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wi593VW0YjKuYD032:-L5x2zKkJxqzYiRw3zJd:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/rethinkstore/rethinkstore.go#L194)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

yes :)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/352)*

**Comment by simonvadee** [comment]
:lgtm:

---

Review status: 28 of 37 files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-:-L5xEmSa5ZyDxDF2Mqso:bnfp4nl)*

**Comment by simonvadee** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/352)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-:-L5xRtEN2LqMr0mbObQt:bnfp4nl)*

**Comment by such** [comment]
HARD FORK!
:lgtm:

---

Reviewed 28 of 37 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[cs/cs.go, line 185 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wNH8o8nhzoOeou730:-L5xSqIhjwz-KePy9Gv4:b-c4fl4p) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L185)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

agreed :+1:
</blockquote></details>

I would keep them for encapsulation but either is fine.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-:-L5xU1kCsl8DEuWWxMvr:b-2lkgxl)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[cs/cs.go, line 141 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wO0fFR3CkrG4xhlDJ:-L5xy2b8w29usDTtmUfe:b-9oi7dm) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L141)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

negative values are allowed (cf. tests)
</blockquote></details>

@such, is it ok for you?

---

*[cs/cs.go, line 185 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wNH8o8nhzoOeou730:-L5xx5XcDJXZ0rdU_VKX:b-rjavwt) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L185)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I would keep them for encapsulation but either is fine.
</blockquote></details>

I prefer remove getter without logic to do not write all unuseful getters.
And I've put `GetPrevLinkHash` and `GetTagsMap` on `LinkMeta`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/352)*

**Comment by such** [comment]
Reviewed 2 of 14 files at r3.
Review status: 31 of 43 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[cs/cs.go, line 141 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-L5wO0fFR3CkrG4xhlDJ:-L5y30dbwTtFEnvcJXIR:b2ni9b4) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9054667d918fec1bf6078fe0e70e8dce4613c27/cs/cs.go#L141)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

@such, is it ok for you?
</blockquote></details>

ok!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/352)*

**Comment by simonvadee** [comment]
:lgtm:

---

Reviewed 14 of 14 files at r3.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-:-L5y8HPyguEp_aneB18Q:bnfp4nl)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 13 of 14 files at r3, 4 of 4 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/352#-:-L5yDDofxZIGORW_Csmi:bnfp4nl)*

**Pull request merged**
