### PR TITLE
changelog: 0.3.0

### PR DESCRIPTION
**Pull request by simonvadee**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/384)

### CODE REVIEW

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/384#-:-L9AHckp55xHzJjnpUQm:bnfp4nl)*

**Comment by such** [comment]
Reviewed 1 of 1 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[CHANGE_LOG.md, line 3 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/384#-L9AM0Ao4-xaS2twBW5l:-L9AM0Ao4-xaS2twBW5m:b-pyuvxo) ([raw file](https://github.com/stratumn/go-indigocore/blob/856789c2eca6d894f811343f06c523c989d8cd02/CHANGE_LOG.md#L3)):*
> ```Markdown
> # Change log
> 
> ## 0.3.0 - BREAKING CHANGES
> ```

we could add that `strat` cli is a bit sexier.
in terms of bugfix, pgstore and couchstore are now compatible with the fossilizers

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/384)*

**Comment by alexppxela** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/384)*

**Comment by simonvadee** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[CHANGE_LOG.md, line 3 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/384#-L9AM0Ao4-xaS2twBW5l:-L9AVewb6ALD_cWbyCHr:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/856789c2eca6d894f811343f06c523c989d8cd02/CHANGE_LOG.md#L3)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

we could add that `strat` cli is a bit sexier.
in terms of bugfix, pgstore and couchstore are now compatible with the fossilizers
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/384)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/384#-:-L9AW3Bh5WHLIDbb-hFm:bnfp4nl)*

**Comment by such** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/384#-:-L9AhR_H-By_AkpQtN1Y:bnfp4nl)*

**Pull request merged**
