### PR TITLE
monitoring: allow custom configuration

### PR DESCRIPTION
**Pull request by t-bast**
Users can configure monitoring parameters via the command-line.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/373)

### CODE REVIEW

**Comment by alexppxela** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tmpop/metrics.go, line 98 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/373#-L8aSACEAkFDPXZyKCMi:-L8aSACEAkFDPXZyKCMj:b-9z5m6i) ([raw file](https://github.com/stratumn/go-indigocore/blob/1c8c0856a2fcf804032d440bcdacb86edcee50f0/tmpop/metrics.go#L98)):*
> ```Go
> 	}
> 
> 	if config.MetricsPort == 0 {
> ```

Why didn't you put 5001 as default value in monitoring/flag?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/373)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[tmpop/metrics.go, line 98 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/373#-L8aSACEAkFDPXZyKCMi:-L8aTN-H1-Dg73_SoBnd:b-2fpk6r) ([raw file](https://github.com/stratumn/go-indigocore/blob/1c8c0856a2fcf804032d440bcdacb86edcee50f0/tmpop/metrics.go#L98)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Why didn't you put 5001 as default value in monitoring/flag?
</blockquote></details>

Because I don't think it's a good default value for all cases...
For httpstore for example we will not honor that value and will instead expose on the same port as the httpstore.
Only TMPoP will have a default value because it doesn't have an http server that we initialize ourselves, other components will reuse the port of their http server.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/373)*

**Comment by alexppxela** [comment]
:lgtm:
Fossilizer monitoring in a next PR.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/373#-:-L8aVVh-2yKaQ7-Wo671:b-3mygea)*

**Comment by such** [comment]
Reviewed 17 of 18 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[monitoring/config.go, line 60 at r2](https://beta.reviewable.io/reviews/stratumn/go-indigocore/373#-L8aZrYx-cZvat9q5aPL:-L8aZrYx-cZvat9q5aPM:bdtia33) ([raw file](https://github.com/stratumn/go-indigocore/blob/20833a11ce88e83fc5644e57227331f412a3208b/monitoring/config.go#L60)):*
> ```Go
> 
> 	if len(config.JaegerEndpoint) == 0 {
> 		config.JaegerEndpoint = "http://jaeger:14268"
> ```

nit: this `string` could be extracted to a `const` (used twice in this package)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/373)*

**Comment by such** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/373#-:-L8a_7V18Za7iQDNmCIy:bnfp4nl)*

**Comment by t-bast** [comment]
Review status: 16 of 18 files reviewed at latest revision, 1 unresolved discussion.

---

*[monitoring/config.go, line 60 at r2](https://beta.reviewable.io/reviews/stratumn/go-indigocore/373#-L8aZrYx-cZvat9q5aPL:-L8afToDDrlQuTV6iEG6:bkfzxvt) ([raw file](https://github.com/stratumn/go-indigocore/blob/20833a11ce88e83fc5644e57227331f412a3208b/monitoring/config.go#L60)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

nit: this `string` could be extracted to a `const` (used twice in this package)
</blockquote></details>

It's cleaner indeed, done

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/373)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/373#-:-L8aoSjP8eEm7eHZHSdn:bnfp4nl)*

**Pull request merged**
