### PR TITLE
validator: add transitions

### PR DESCRIPTION
**Pull request by alexppxela**
Implementation of SRP4.
Validation of transitions.

Here is a rule example:
```
{
    "auction": {
        "pki": {},
        "types": {
            "initState": {
                "transitions": {
                    "initialize" : [""]
                }
            },
            "OrderOnMarket": {
                "transitions": {
                    "sendOrder" : ["initState", "OrderOnMarket"]
                }
            },
            "OrderCanceled": {
                "transitions": {
                    "cancel" : ["initState", "OrderOnMarket"]
                }
            }
        }
    }
}

```

A chainscript type is the state.
Each state has a list of possible transitions defined as _actionName_ and the list of allowed previous states.
An empty previous state is necessary to create the first link of a map
A final state is a state which is not defined in any allowed previous state.

A next PR will come once this PR will be merged to make transition validation mandatory.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/354)

### CODE REVIEW

**Comment by such** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[validator/configloader_test.go, line 161 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/354#-L6uVkSZC-EuLyd1JE0T:-L6uVkSZC-EuLyd1JE0U:b-oce0mr) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9163944d1f142bf02d81d60a4e2528656f09e22/validator/configloader_test.go#L161)):*
> ```Go
> func TestLoadValidators_Error(t *testing.T) {
> 
> 	t.Run("Missing link type", func(T *testing.T) {
> ```

Missing process rather than link type.

---

*[validator/transition.go, line 58 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/354#-L6uWLVD60lLz3kp2ly5:-L6uWLVD60lLz3kp2ly6:b-mdfhaf) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9163944d1f142bf02d81d60a4e2528656f09e22/validator/transition.go#L58)):*
> ```Go
> }
> 
> // Validate checks that the provided dignatures match the required ones.
> ```

I don't think this comment is up to date. If it was copy pasted, there was a typo (dignatures) in the original one!

---

*[validator/transition.go, line 65 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/354#-L6uWfXdAqkj1RdltwDu:-L6uWfXdAqkj1RdltwDv:b-dql43l) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9163944d1f142bf02d81d60a4e2528656f09e22/validator/transition.go#L65)):*
> ```Go
> 	}
> 
> 	transitions, found := tv.Transitions[link.Meta.Action]
> ```

I don't think we should rely on Action here. It's just there to be more user friendly in the `rules.json` but it's an implementation detail of the agent at this point. We should just check that the type parent of the parent belongs to one of the allowed ancestors. We might want to optimize the parsing of the configuration to optimize this lookup.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/354)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[validator/configloader_test.go, line 161 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/354#-L6uVkSZC-EuLyd1JE0T:-L6uY8BLBYs86nFyAoRJ:b6wvyll) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9163944d1f142bf02d81d60a4e2528656f09e22/validator/configloader_test.go#L161)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

Missing process rather than link type.
</blockquote></details>

copy/paste was not perfect
Done.

---

*[validator/transition.go, line 58 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/354#-L6uWLVD60lLz3kp2ly5:-L6uZdjc8eNtu0GVEMW0:b-886gsx) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9163944d1f142bf02d81d60a4e2528656f09e22/validator/transition.go#L58)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I don't think this comment is up to date. If it was copy pasted, there was a typo (dignatures) in the original one!
</blockquote></details>

Fixed

---

*[validator/transition.go, line 65 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/354#-L6uWfXdAqkj1RdltwDu:-L6uZmLYCO8RfiYshS1k:b-y5gq1v) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9163944d1f142bf02d81d60a4e2528656f09e22/validator/transition.go#L65)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I don't think we should rely on Action here. It's just there to be more user friendly in the `rules.json` but it's an implementation detail of the agent at this point. We should just check that the type parent of the parent belongs to one of the allowed ancestors. We might want to optimize the parsing of the configuration to optimize this lookup.
</blockquote></details>

Good point but I don't think action is just an agent implementation detail.
I think that the action should add some information on state so it can be verified by the schema validator but when a process has shortcuts, I do not think that we want to allow bypassing a part of the process.

For example in transition_test.go from `createdProduct` to `signedFinalProduct`, it is possible to `approve` but don't `sign` to be at the final state. In agent `approve` action will send an email to manager to explain why the procedure was bypassed. If we do not check action, we can lose this information if someone hacked the agent.

I understand your point but I think that if we do not check the couple prevState/Action, it is possible to lose traceability information. If we do not check the couple, I think we should remove Link.Meta.Action.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/354)*

**Comment by such** [comment]
Review status: 7 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[validator/configloader_test.go, line 161 at r2](https://beta.reviewable.io/reviews/stratumn/go-indigocore/354#-L6umLC34TTS1CEX8yow:-L6umLC34TTS1CEX8yox:b-qd1com) ([raw file](https://github.com/stratumn/go-indigocore/blob/d9b18c989ec3758a28c8055a607d4d7c197175bc/validator/configloader_test.go#L161)):*
> ```Go
> func TestLoadValidators_Error(t *testing.T) {
> 
> 	t.Run("Missing process type", func(T *testing.T) {
> ```

nit: it's just "Missing process" I think :)

---

*[validator/transition.go, line 65 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/354#-L6uWfXdAqkj1RdltwDu:-L6uml-9-iWX4VsI_ekN:bvw3gr5) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9163944d1f142bf02d81d60a4e2528656f09e22/validator/transition.go#L65)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Good point but I don't think action is just an agent implementation detail.
I think that the action should add some information on state so it can be verified by the schema validator but when a process has shortcuts, I do not think that we want to allow bypassing a part of the process.

For example in transition_test.go from `createdProduct` to `signedFinalProduct`, it is possible to `approve` but don't `sign` to be at the final state. In agent `approve` action will send an email to manager to explain why the procedure was bypassed. If we do not check action, we can lose this information if someone hacked the agent.

I understand your point but I think that if we do not check the couple prevState/Action, it is possible to lose traceability information. If we do not check the couple, I think we should remove Link.Meta.Action.
</blockquote></details>

I feel like it's a battle I'm starting to lose... @azuenko has been pushing for what you described but we had kinda decided to keep it simple for now.
I'm not sure I understand your example even though I can see the benefit of validating the couple prevState/Action (what @azuenko calls a "route"). I'm just worried this provides a false sense of added security. But I totally open to the discussion.
@azuenko , @t-bast, @jeremie-stratumn, @simonvadee what do you think?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/354)*

**Comment by simonvadee** [comment]
*[validator/transition.go, line 65 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/354#-L6uWfXdAqkj1RdltwDu:-L6ulgBsTRfimUe8D0Si:b-qou65l) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9163944d1f142bf02d81d60a4e2528656f09e22/validator/transition.go#L65)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I feel like it's a battle I'm starting to lose... @azuenko has been pushing for what you described but we had kinda decided to keep it simple for now.
I'm not sure I understand your example even though I can see the benefit of validating the couple prevState/Action (what @azuenko calls a "route"). I'm just worried this provides a false sense of added security. But I totally open to the discussion.
@azuenko , @t-bast, @jeremie-stratumn, @simonvadee what do you think?
</blockquote></details>

some of the points from the discussion alexandre and I had :
 - we should not consider `link.meta.action` as a trustable source of information since it is modified in the agent.
 - if there are specific requirements to a transition validation (as in the above example with `createdProduct`), they will be validated by the validation language rather than on the transition name, which can be falsified.
 - the traceability information should always be available in `link.state` wether it's a "standard" procedure or a more "custom" one.

I agree that it introduce a security breach since we have no way of knowing which action was actually executed by the agent.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/354)*

**Comment by alexppxela** [comment]
*[validator/configloader_test.go, line 161 at r2](https://reviewable.io:443/reviews/stratumn/go-indigocore/354#-L6umLC34TTS1CEX8yow:-L6upBTCFD_x0MYNfQ_I:b-qipnh3) ([raw file](https://github.com/stratumn/go-indigocore/blob/d9b18c989ec3758a28c8055a607d4d7c197175bc/validator/configloader_test.go#L161)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

nit: it's just "Missing process" I think :)
</blockquote></details>

:face_with_head_bandage: :gun: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/354)*

**Comment by such** [comment]
Review status: 7 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[validator/transition.go, line 65 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/354#-L6uWfXdAqkj1RdltwDu:-L6upP2N87cV3soKHFB7:b-cqfl16) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9163944d1f142bf02d81d60a4e2528656f09e22/validator/transition.go#L65)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

some of the points from the discussion alexandre and I had :
 - we should not consider `link.meta.action` as a trustable source of information since it is modified in the agent.
 - if there are specific requirements to a transition validation (as in the above example with `createdProduct`), they will be validated by the validation language rather than on the transition name, which can be falsified.
 - the traceability information should always be available in `link.state` wether it's a "standard" procedure or a more "custom" one.

I agree that it introduce a security breach since we have no way of knowing which action was actually executed by the agent.
</blockquote></details>

My point is that it's not really a security breach since this field is never reliable... It would be only if the agent was on a trusted enclave or something...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/354)*

**Comment by alexppxela** [comment]
*[validator/transition.go, line 65 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/354#-L6uWfXdAqkj1RdltwDu:-L6ut1V-JfYO3-p5Hkdd:bjupvvw) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9163944d1f142bf02d81d60a4e2528656f09e22/validator/transition.go#L65)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

My point is that it's not really a security breach since this field is never reliable... It would be only if the agent was on a trusted enclave or something...
</blockquote></details>

@such you win ;)
We spoke with @azuenko and @simonvadee and we said that we need to keep rules as simple as possible to begin and enrich it later if needed. so, I'll change the transitions as.
```
{
    "auction": {
        "types": {
            "OrderOnMarket": {
                "transitions": ["initState", "OrderOnMarket", ""]
            },
            ...
}
```
If action name is needed by validation UI, it could add more information in json.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/354)*

**Comment by azuenko** [comment]
Review status: 7 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[validator/transition.go, line 65 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/354#-L6uWfXdAqkj1RdltwDu:-L6utEaqBWUGQf9LwD0g:bb6ywmx) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9163944d1f142bf02d81d60a4e2528656f09e22/validator/transition.go#L65)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

@such you win ;)
We spoke with @azuenko and @simonvadee and we said that we need to keep rules as simple as possible to begin and enrich it later if needed. so, I'll change the transitions as.
```
{
    "auction": {
        "types": {
            "OrderOnMarket": {
                "transitions": ["initState", "OrderOnMarket", ""]
            },
            ...
}
```
If action name is needed by validation UI, it could add more information in json.
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/354)*

**Comment by simonvadee** [comment]
Reviewed 10 of 10 files at r1.
Review status: 7 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[validator/transition_test.go, line 87 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/354#-L6utf8l8j9C28Q3TcIk:-L6utf8l8j9C28Q3TcIl:bhp8buc) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9163944d1f142bf02d81d60a4e2528656f09e22/validator/transition_test.go#L87)):*
> ```Go
> 	require.NoError(t, err)
> 
> 	append := func(prevLink *cs.Link, state, action string) *cs.Link {
> ```

nit: pick an other name since `append` is already defined in the standard lib

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/354)*

**Comment by alexppxela** [comment]
Review status: 4 of 10 files reviewed at latest revision, 2 unresolved discussions.

---

*[validator/transition_test.go, line 87 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/354#-L6utf8l8j9C28Q3TcIk:-L6vV1mDFiK4gryZXcWY:bb7pcsz) ([raw file](https://github.com/stratumn/go-indigocore/blob/a9163944d1f142bf02d81d60a4e2528656f09e22/validator/transition_test.go#L87)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

nit: pick an other name since `append` is already defined in the standard lib
</blockquote></details>

true

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/354)*

**Comment by simonvadee** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/354#-:-L6v_VK74kixxEBHvx6E:bnfp4nl)*

**Comment by such** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/354#-:-L6vaQp7H9buUA2KpcpD:bnfp4nl)*

**Pull request merged**
