### PR TITLE
evidences: split tendermint dependency

### PR DESCRIPTION
**Pull request by t-bast**
I wanted to run the storetestcases in Alice (on the Alice store wrapper) and it ended up importing almost all of Tendermint inside Alice, which is really not desirable.
I think it's good to create a clear boundary with everything Tendermint-specific in go-indigocore, to allow many pieces to be used outside without pulling any of the Tendermint dependencies.
It's a bit painful to have to remember to do a blank import on all the evidence packages in the cmds that use them, but I think that it's cleaner as a dependency management point of view (only import these in cmds' main.go file).

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/398)

### CODE REVIEW

**Comment by such** [comment]
At some point we'll really need to have either cmd tests somehow or system tests!

:lgtm:

---

Reviewed 26 of 27 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[cs/evidences/evidences.go, line 101 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/398#-LAN39Q7CdxJBhiYKBy-:-LAN39Q7CdxJBhiYKBy0:b-k5wh4c) ([raw file](https://github.com/stratumn/go-indigocore/blob/bfd214f6691bc0999a71c78a6f24988c7e26f64e/cs/evidences/evidences.go#L101)):*
> ```Go
> 		return &p, nil
> 	}
> 	cs.DeserializeMethods[BcBatchFossilizerName] = func(rawProof json.RawMessage) (cs.Proof, error) {
> ```

For consistency wouldn't that make sense to move those initialization in their fossilizer package as well?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/398#-:-LAN3N721gufSbFYczn6:b4mlyg1)*

**Comment by t-bast** [comment]
I agree, these would be useful!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[cs/evidences/evidences.go, line 101 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/398#-LAN39Q7CdxJBhiYKBy-:-LAN3jkS7rZOviJkGFvA:b-dbk3x0) ([raw file](https://github.com/stratumn/go-indigocore/blob/bfd214f6691bc0999a71c78a6f24988c7e26f64e/cs/evidences/evidences.go#L101)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

For consistency wouldn't that make sense to move those initialization in their fossilizer package as well?
</blockquote></details>

I think it would make sense indeed. I'll do it in this PR to keep the change contained.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/398#-:-LAN3e8j2QbAjIbH0yA6:b-4rihza)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 26 of 27 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/398#-:-LAN5FBp0r_IL4oJeVR5:bnfp4nl)*

**Comment by simonvadee** [comment]
:lgtm:

---

Reviewed 26 of 27 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/398#-:-LANA5fn-mpBqpWnbDbW:bnfp4nl)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 28 of 29 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/398#-:-LANDVU2E9bAj7boSt3a:bnfp4nl)*

**Comment by simonvadee** [comment]
:lgtm:

---

Reviewed 28 of 29 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/398#-:-LANW_UuE6PuXtwvofF9:bnfp4nl)*

**Pull request merged**
