### PR TITLE
signatures, cs: sign messages and links

### PR DESCRIPTION
**Pull request by simonvadee**
This is needed so we can use indigocore `signatures` package in indigotrace.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/367)

### CODE REVIEW

**Comment by t-bast** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cs/signature.go, line 52 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/367#-L7Z-hbwBYZkJ41G7-Eu:-L7Z-hbxBq2LBwT6inKb:b-qqkpy4) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signature.go#L52)):*
> ```Go
> 	}
> 	if payload == nil {
> 		return nil, errors.New("JMESPATH query does not match any link data")
> ```

nit: I think it's good to define our custom errors as vars at the package level.
This way clients (and tests) can test for that specific error which is handy.

---

*[cs/signature_test.go, line 63 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/367#-L7Z05X_DlbmXCt4FP6v:-L7Z05X_DlbmXCt4FP6w:bxs3jvi) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signature_test.go#L63)):*
> ```Go
> 		sig, err := cs.NewSignature(sig.Ed25519, payloadPath, priv[:], link)
> 		assert.NoError(t, err)
> 		assert.NoError(t, sig.Verify(link), "signature verificdation failed")
> ```

nit: typo

---

*[cs/signatures/schemes.go, line 129 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/367#-L7Z0OCK0dQhX3K3U8CQ:-L7Z0OCK0dQhX3K3U8CR:b-251qww) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signatures/schemes.go#L129)):*
> ```Go
> 	case Ed25519:
> 		if len(privateKey) != ed25519.PrivateKeySize {
> 			return "", "", errors.Errorf("%s private key lenght must be %d, got %d", Ed25519, ed25519.PrivateKeySize, len(privateKey))
> ```

nit: length

---

*[cs/signatures/schemes.go, line 133 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/367#-L7Z0YC4ANfgPWelVini:-L7Z0YC4ANfgPWelVinj:b-s5jeut) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signatures/schemes.go#L133)):*
> ```Go
> 		pk := ed25519.PrivateKey(privateKey)
> 
> 		publicKey = base64.StdEncoding.EncodeToString(pk.Public().(ed25519.PublicKey))
> ```

Shouldn't we directly use EncodeToString(pk.Public().Marshal()) or something equivalent to "Marshal"/"Bytes"? I don't think we should dive to the concrete ed25519.PublicKey type but rather use a Marshaling offered at the PublicKey interface level (if there is one).

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/367)*

**Comment by piedup** [comment]
I am currently redoing the Trace pki part where I have tried to use standards for key encoding.

IMO we should not use custom signatureType strings to define what type of signature is used. Instead we should use the existing standards (https://tools.ietf.org/html/rfc5958). The private keys should be encoded using DER ASN.1, where key algorithm (and curves if necessary) are directly encoded with the actual key.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/367#-:-L7Z12XBIW3Q-vvotuCX:b-5nfur2)*

**Comment by alexppxela** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[cs/signature_test.go, line 63 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/367#-L7Z0QRXDeiBEGoNQe9d:-L7Z0QRXDeiBEGoNQe9e:bcgwzac) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signature_test.go#L63)):*
> ```Go
> 		sig, err := cs.NewSignature(sig.Ed25519, payloadPath, priv[:], link)
> 		assert.NoError(t, err)
> 		assert.NoError(t, sig.Verify(link), "signature verificdation failed")
> ```

typo: _verificdation_

---

*[cs/signatures/schemes.go, line 119 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/367#-L7Z1auju_6-7hAxuz6s:-L7Z1auju_6-7hAxuz6t:bedaryp) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signatures/schemes.go#L119)):*
> ```Go
> // _______________________________________
> // Private keys must be encoded as follows:
> // - Ed25519: no encoding necessary, private key length should be 64 bytes.
> ```

typo: _lenght_

---

*[cs/signatures/schemes.go, line 129 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/367#-L7Z1AsLsB8DgpBEsgs5:-L7Z1AsMtiS8RjVOaXRv:bedaryp) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signatures/schemes.go#L129)):*
> ```Go
> 	case Ed25519:
> 		if len(privateKey) != ed25519.PrivateKeySize {
> 			return "", "", errors.Errorf("%s private key lenght must be %d, got %d", Ed25519, ed25519.PrivateKeySize, len(privateKey))
> ```

typo: _lenght_

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/367)*

**Comment by simonvadee** [comment]
After coordinating with @piedup, we decided to extract the key / signatures / certificate code to a dedicated repository.
I'll merge this one and wait for the new repo before updating indigotrace.

---

Review status: 0 of 4 files reviewed at latest revision, 8 unresolved discussions.

---

*[cs/signature.go, line 52 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/367#-L7Z-hbwBYZkJ41G7-Eu:-L7Z1sMCkqg09JLm0yMn:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signature.go#L52)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: I think it's good to define our custom errors as vars at the package level.
This way clients (and tests) can test for that specific error which is handy.
</blockquote></details>

Done.

---

*[cs/signature_test.go, line 63 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/367#-L7Z05X_DlbmXCt4FP6v:-L7Z1qnONll5gbGmuFyx:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signature_test.go#L63)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: typo
</blockquote></details>

Done.

---

*[cs/signature_test.go, line 63 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/367#-L7Z0QRXDeiBEGoNQe9d:-L7Z2k80YZFt2YrTqMq3:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signature_test.go#L63)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

typo: _verificdation_
</blockquote></details>

Done.

---

*[cs/signatures/schemes.go, line 119 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/367#-L7Z1auju_6-7hAxuz6s:-L7Z2wpeBOUpO1l_RoZE:bftqx2) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signatures/schemes.go#L119)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

typo: _lenght_
</blockquote></details>

I know I'm quite bad at spelling `length` correctly but I believe I succeeded there !

---

*[cs/signatures/schemes.go, line 129 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/367#-L7Z0OCK0dQhX3K3U8CQ:-L7Z1mq7fLmtix9yP_0J:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signatures/schemes.go#L129)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: length
</blockquote></details>

Done.

---

*[cs/signatures/schemes.go, line 129 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/367#-L7Z1AsLsB8DgpBEsgs5:-L7Z3D1O_VBG2JH8L8tS:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signatures/schemes.go#L129)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

typo: _lenght_
</blockquote></details>

Done.

---

*[cs/signatures/schemes.go, line 133 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/367#-L7Z0YC4ANfgPWelVini:-L7Z3m9XWFMueYIomczw:b3peugm) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signatures/schemes.go#L133)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Shouldn't we directly use EncodeToString(pk.Public().Marshal()) or something equivalent to "Marshal"/"Bytes"? I don't think we should dive to the concrete ed25519.PublicKey type but rather use a Marshaling offered at the PublicKey interface level (if there is one).
</blockquote></details>

I would agree if such a function existed ! https://golang.org/pkg/crypto/#PublicKey
However, since the `PublicKey` interface covers multiple crypto schemes, there is no general marshaling, although several kinds of serialization may be used (ASN1, PEM...)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/367#-:-L7ZAt-nZdKIsbc41IK8:b3u77at)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cs/signatures/schemes.go, line 119 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/367#-L7Z1auju_6-7hAxuz6s:-L7ZUjK5AxQiQpSY5WQw:b32vin) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signatures/schemes.go#L119)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

I know I'm quite bad at spelling `length` correctly but I believe I succeeded there !
</blockquote></details>

:D

---

*[cs/signatures/schemes.go, line 133 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/367#-L7Z0YC4ANfgPWelVini:-L7ZUnwq9zPcglotrU6_:by2ghkw) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signatures/schemes.go#L133)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

I would agree if such a function existed ! https://golang.org/pkg/crypto/#PublicKey
However, since the `PublicKey` interface covers multiple crypto schemes, there is no general marshaling, although several kinds of serialization may be used (ASN1, PEM...)
</blockquote></details>

If we don't have a choice then of course it's fine :)
And anyway if we adopt what Pierre suggests this issue will disappear

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/367#-:-L7ZUviw6wvs_lY-J5EQ:bnfp4nl)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[cs/signatures/schemes.go, line 119 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/367#-L7Z1auju_6-7hAxuz6s:-L7ZVqtV6paqYm4wbub-:b-saaxc7) ([raw file](https://github.com/stratumn/go-indigocore/blob/d007c5686c9519e37b8f8b98a89f8fe7471a6b26/cs/signatures/schemes.go#L119)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

:D
</blockquote></details>

It might be my eyes which has crossed letters and words ;)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/367#-:-L7ZW1MXCNOuyjsAk_nf:bnfp4nl)*

**Pull request merged**
