### PR TITLE
validator: make transition validation mandatory

### PR DESCRIPTION
**Pull request by alexppxela**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/355)

### CODE REVIEW

**Comment by t-bast** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[validator/configloader.go, line 163 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-L6vqiOJSftcCr5PVahn:-L6vqiOKzAYSw9a6hCO8:b-xk01ee) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/configloader.go#L163)):*
> ```Go
> 			validators = append(validators, newTransitionValidator(baseConfig, val.Transitions))
> 		} else {
> 			validators = append(validators, newInvalidValidator(baseConfig, "transition validator is mandatory"))
> ```

Once that change is checked-in, do we still have a way to create a simple agent that allows absolutely no structure on the state?
If I want to be able to send segments with whatever state I wish and no specific transitions for one of my processes, will that still be possible?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[validator/configloader.go, line 163 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-L6vqiOJSftcCr5PVahn:-L6vrt7Z7X1U-IRQs75Z:bxlw8kl) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/configloader.go#L163)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Once that change is checked-in, do we still have a way to create a simple agent that allows absolutely no structure on the state?
If I want to be able to send segments with whatever state I wish and no specific transitions for one of my processes, will that still be possible?
</blockquote></details>

if you don't have any `rules.json` right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355)*

**Comment by such** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355)*

**Comment by such** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-:-L6vsgYlTHpfTAZxP921:bnfp4nl)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[validator/configloader.go, line 163 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-L6vqiOJSftcCr5PVahn:-L6vsba5664Ri6ds2Sex:bxr8y6i) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/configloader.go#L163)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

if you don't have any `rules.json` right?
</blockquote></details>

If that's the case perfect, but I'm afraid that if you don't have any rules.json the store fails to start, doesn't it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355)*

**Comment by alexppxela** [comment]
*[validator/configloader.go, line 163 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-L6vqiOJSftcCr5PVahn:-L6vrzL81lfQEKzkqKBz:bs0fspw) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/configloader.go#L163)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

If that's the case perfect, but I'm afraid that if you don't have any rules.json the store fails to start, doesn't it?
</blockquote></details>

It is not possible. I removed the "*" transition because it was misunderstood for signatures.
rules.json will disappear with governance. But we can keep the same behaviour (if no governance segment is inserted, no validation_

Without * or validation disabled, if no transitions are defined, your store will start but all your links will be rejected.

Do you think it is too extremist?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[validator/configloader.go, line 163 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-L6vqiOJSftcCr5PVahn:-L6vvSdAplzwQVdpbeEa:b-lz859e) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/configloader.go#L163)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

It is not possible. I removed the "*" transition because it was misunderstood for signatures.
rules.json will disappear with governance. But we can keep the same behaviour (if no governance segment is inserted, no validation_

Without * or validation disabled, if no transitions are defined, your store will start but all your links will be rejected.

Do you think it is too extremist?
</blockquote></details>

I think it'd be fine to keep a fully open mode (no rules)
ⒶⒶⒶ

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[validator/configloader.go, line 163 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-L6vqiOJSftcCr5PVahn:-L6vyDRmRUInb6qayhis:bjq72xw) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/configloader.go#L163)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I think it'd be fine to keep a fully open mode (no rules)
ⒶⒶⒶ
</blockquote></details>

I agree, I think we need a free mode where there's no validation at all.
As a newcomer to Indigo, you want to be able to experiment first with a free system, than add your validations once you're a bit comfortable with the system.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355)*

**Comment by simonvadee** [comment]
*[validator/configloader.go, line 163 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-L6vqiOJSftcCr5PVahn:-L6wBqQyKa1XniyHmPdK:bkwl1ov) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/configloader.go#L163)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

I agree, I think we need a free mode where there's no validation at all.
As a newcomer to Indigo, you want to be able to experiment first with a free system, than add your validations once you're a bit comfortable with the system.
</blockquote></details>

just to be clear: segments won't be rejected if `rules.json` (or governance map) does not exist for a process (free mode).
However I agree that we should be able to define rules without having to specify state transitions (aka: drop this `else`)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[validator/configloader.go, line 163 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-L6vqiOJSftcCr5PVahn:-L6wDQh9skwt6J44SlO3:b-6dlf4r) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/configloader.go#L163)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

just to be clear: segments won't be rejected if `rules.json` (or governance map) does not exist for a process (free mode).
However I agree that we should be able to define rules without having to specify state transitions (aka: drop this `else`)
</blockquote></details>

I don't have a strong opinion.  I'm not sure the case will present itself once we have a validation UI since all types will have to be linked somehow (or so I think). What you're suggesting is defaulting on "*" basically?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355)*

**Comment by simonvadee** [comment]
*[validator/configloader.go, line 163 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-L6vqiOJSftcCr5PVahn:-L6wEGkOC8Ss1GJh2FhU:b-m0v00p) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/configloader.go#L163)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I don't have a strong opinion.  I'm not sure the case will present itself once we have a validation UI since all types will have to be linked somehow (or so I think). What you're suggesting is defaulting on "*" basically?
</blockquote></details>

You're right, with validation UI links will always declare a type. But if we want to port validation on trace for instance (even if it's centralized), we may want to apply schema/signature validation on events, whereas transition validation is useless since it is an append-only process.

Defaulting on "*" is equivalent to not having a transition validator, so yes I guess that's what I'm suggesting. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355)*

**Comment by simonvadee** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[utils/filetesting.go, line 26 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-L6wA3aE62gAV_W-KfXw:-L6wA3aE62gAV_W-KfXx:bk6otdi) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/utils/filetesting.go#L26)):*
> ```Go
> // CreateTempFile creates a temporary file for tests with data as content.
> func CreateTempFile(t *testing.T, data string) string {
> 	tmpfile, err := ioutil.TempFile("", "validator-tmpfile")
> ```

nit: maybe the name should not mention "validator"

---

*[validator/invalid.go, line 27 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-L6wCv6GoSsykRMzAQu4:-L6wCv6GoSsykRMzAQu5:b3sb9u3) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/invalid.go#L27)):*
> ```Go
> 
> // invalidValidator never validates a link.
> type invalidValidator struct {
> ```

I'm not sure this is the best way to handle errors in the validation rules, I'd rather throw an error while loading the validation file, what do you think ?

---

*[validator/validator_test.go, line 52 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-L6wDq7aidGPODEGf_ue:-L6wDq7aidGPODEGf_uf:b1p1sqs) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/validator_test.go#L52)):*
> ```Go
> 			Process: "auction",
> 			Type:    "init",
> 			Action:  "initialize",
> ```

do we still need the action or is it just to make the example clearer ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[validator/configloader.go, line 163 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-L6vqiOJSftcCr5PVahn:-L6wH5ca75r8GHXCJ732:b-i4wyug) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/configloader.go#L163)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

You're right, with validation UI links will always declare a type. But if we want to port validation on trace for instance (even if it's centralized), we may want to apply schema/signature validation on events, whereas transition validation is useless since it is an append-only process.

Defaulting on "*" is equivalent to not having a transition validator, so yes I guess that's what I'm suggesting. 
</blockquote></details>

I think it will actually be very important for Trace. You'll want to prevent someone from appending as long as another step hasn't been created.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355)*

**Comment by such** [comment]
Now that we've removed the action name from the configuration I feel like the name `transitions` is a bit confusing.
I can see a few different options:

- `parents`
- `previous` or `prev` (because `prevLinkHash`)
- `ancestors` (maybe unclear because we're actually looking only at direct ancestors)

What do you think?

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/355#-:-L6zi8tpDIbtmZBXOIIK:b-8bp1su)*

**Comment by simonvadee** [comment]
I like `parents`, and I think `previous` induces a bit of confusion with the link hash.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[validator/configloader.go, line 163 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-L6vqiOJSftcCr5PVahn:-L6zkOpem_Pn5q-Dn61r:bnykkkn) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/configloader.go#L163)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I think it will actually be very important for Trace. You'll want to prevent someone from appending as long as another step hasn't been created.
</blockquote></details>

It's still unclear to me how we will design a process (with different steps) in trace. Do we plan to use the validation UI in trace ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-:-L6zjaEHQMNcc8xh2LVd:b33ibya)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[validator/configloader.go, line 163 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-L6vqiOJSftcCr5PVahn:-L6zlZnCfy3-z-NClxl1:b-bfq9ue) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/configloader.go#L163)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

It's still unclear to me how we will design a process (with different steps) in trace. Do we plan to use the validation UI in trace ?
</blockquote></details>

Maybe a simplified version of the validation UI. The way I see it, each Trace "Input" would produce "Events" of a single "Type" for IndigoCore. And so you would be able to tell: this input cannot log an event before an event from this other input has been logged.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355)*

**Comment by simonvadee** [comment]
*[validator/configloader.go, line 163 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-L6vqiOJSftcCr5PVahn:-L6zo6EDdoTTSwK-LTor:bcgj1ah) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/configloader.go#L163)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

Maybe a simplified version of the validation UI. The way I see it, each Trace "Input" would produce "Events" of a single "Type" for IndigoCore. And so you would be able to tell: this input cannot log an event before an event from this other input has been logged.
</blockquote></details>

right, makes sense !

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[utils/filetesting.go, line 26 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/355#-L6wA3aE62gAV_W-KfXw:-L6zqJnX3lufD36lBiwR:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/utils/filetesting.go#L26)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

nit: maybe the name should not mention "validator"
</blockquote></details>

Done.

---

*[validator/configloader.go, line 163 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/355#-L6vqiOJSftcCr5PVahn:-L6zqpC21ROghFk8juT0:b-nb1gun) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/configloader.go#L163)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

right, makes sense !
</blockquote></details>

I had in mind to forbid partial state machine descrtiption.
So now:
- no rules.json & no rule governance segment -> no validation
- zero transition definition -> no transition validation
- all linkType transition defined -> transition validation enabled
- some linkType transition missing -> error at init

---

*[validator/invalid.go, line 27 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/355#-L6wCv6GoSsykRMzAQu4:-L6zuG2388IkUXJLVoE7:b6p1d1j) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/invalid.go#L27)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

I'm not sure this is the best way to handle errors in the validation rules, I'd rather throw an error while loading the validation file, what do you think ?
</blockquote></details>

I'm shared between the two options. I like the possibility to allow partial validation. But for UX is easier if it is not possible to add a bad configuration. So, I'll remove it

---

*[validator/validator_test.go, line 52 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/355#-L6wDq7aidGPODEGf_ue:-L6zuxaAAT5p_Ai5fhFh:bvosqft) ([raw file](https://github.com/stratumn/go-indigocore/blob/ffbcf383c5c98099b21ea1e725f81afc7817411c/validator/validator_test.go#L52)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

do we still need the action or is it just to make the example clearer ?
</blockquote></details>

I forgot to update tests after action usage removal

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/355)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/355#-:-L7-3GOaBpamnPgSGWsg:bnfp4nl)*

**Comment by simonvadee** [comment]
:lgtm:

---

Reviewed 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/355#-:-L7-3zosudzKKOrDt58G:bnfp4nl)*

**Pull request merged**
