### PR TITLE
cstesting: add option in LinkBuilder

### PR DESCRIPTION
**Pull request by simonvadee**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/419)

### CODE REVIEW

**Comment by alexppxela** [comment]
I think I'd had 2 more signatures to keep Sign() and RandomSignatures() without pauloadPath

---

Reviewed 10 of 10 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @bejito)

---



*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/419#-:-LFXg9JzDPKegC0zTv56:b-1egv1y)*

**Comment by bejito** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/419#-:-LFXmvTF0ZbD4HZ6_DDL:bnfp4nl)*

**Comment by t-bast** [comment]
Given that most users of this Sign() method won't cared what payload path is signed, I would prefer creating another function instead of forcing a required parameter on the Sign() one. You could add a SignPath(path string) method so that you're not introducing a breaking change. 

---

Reviewed 10 of 10 files at r1.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/419#-:-LFYK1eL-LZPXhxoCP8C:b2x5ovk)*

**Comment by simonvadee** [comment]
I agree with your comments, just added a few new functions !

---

Review status: 1 of 5 files reviewed, all discussions resolved (waiting on @alexppxela, @bejito, and @t-bast)

---



*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/419#-:-LFaWouy7S9ImARLFyyG:b-7uo3ck)*

**Comment by alexppxela** [comment]
Reviewed 4 of 9 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @simonvadee)

---

*[cs/cstesting/builder.go, line 145 at r2](https://reviewable.io/reviews/stratumn/go-indigocore/419#-LFaXlca2EAbyA18qqZl:-LFaXlca2EAbyA18qqZm:b-7ibb2r) ([raw file](https://github.com/stratumn/go-indigocore/blob/70c8900eabc01ea282285844614ddc73a9e8cbf7/cs/cstesting/builder.go#L145)):*
> ```Go
> 
> // SignWithKey signs the link with the provided private key.
> func (lb *LinkBuilder) SignWithKey(priv crypto.PrivateKey, payloadPath string) *LinkBuilder {
> ```

payload arg is not necessary

---

*[tmstore/tmstore_test.go, line 111 at r2](https://reviewable.io/reviews/stratumn/go-indigocore/419#-LFaXvBv7Ib23d1_HHqz:-LFaXvBv7Ib23d1_HHr-:bx1ml1h) ([raw file](https://github.com/stratumn/go-indigocore/blob/70c8900eabc01ea282285844614ddc73a9e8cbf7/tmstore/tmstore_test.go#L111)):*
> ```Go
> 				WithType("init").
> 				WithState(state).
> 				SignWithKey(ITPrivateKey, "[state, meta]").
> ```

Do not give paths in SignWithKey

---


*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/419)*

**Comment by simonvadee** [comment]
Review status: all files reviewed, 2 unresolved discussions (waiting on @alexppxela)

---

*[cs/cstesting/builder.go, line 145 at r2](https://reviewable.io/reviews/stratumn/go-indigocore/419#-LFaXlca2EAbyA18qqZl:-LFaZ1eJE3-Veczzu8Xx:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/70c8900eabc01ea282285844614ddc73a9e8cbf7/cs/cstesting/builder.go#L145)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

payload arg is not necessary
</blockquote></details>

Done.

---

*[tmstore/tmstore_test.go, line 111 at r2](https://reviewable.io/reviews/stratumn/go-indigocore/419#-LFaXvBv7Ib23d1_HHqz:-LFaZUI16KYPDbeRFFh-:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/70c8900eabc01ea282285844614ddc73a9e8cbf7/tmstore/tmstore_test.go#L111)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Do not give paths in SignWithKey
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/419)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 9 files at r2, 2 of 4 files at r3.
Review status: all files reviewed, 2 unresolved discussions (waiting on @alexppxela)

---



*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/419#-:-LFa_aKU1AuTv5xFVw6p:bnfp4nl)*

**Comment by alexppxela** [comment]
:lgtm:

---

Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/419#-:-LFa_mWe82kBHVL_q_ui:bnfp4nl)*

**Pull request merged**
