### PR TITLE
Load validator rules asynchronously

### PR DESCRIPTION
**Pull request by alexppxela**
This PR avoids reading the validator rules file at each begin block. There is a file watcher on file which reloads validators
The library fsnotify is used and will be removed in a next PR prefering reading data from segments.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/345)

### CODE REVIEW

**Comment by alexppxela** [comment]
Review status: 0 of 6 files reviewed at latest revision, 1 unresolved discussion.

---

*[tmstore/tmstore_test.go, line 98 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/345#-L5F-nsIie1SBor-JhSl:-L5F-nsIie1SBor-JhSm:b-tgk1x6) ([raw file](https://github.com/stratumn/go-indigocore/blob/8103fca14122b488c15bd215764178e5352ba940/tmstore/tmstore_test.go#L98)):*
> ```Go
> 
> 		updateValidatorRulesFile(t, filepath.Join("testdata", "rules.json"), rulesFilename)
> 		time.Sleep(time.Second)
> ```

Sorry, fsnotify is not target, aweful sleeps will be deleted in next PR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/345)*

**Comment by t-bast** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tmpop/state.go, line 68 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/345#-L5IUMrDT_lcmG_4U3mZ:-L5IUMrEBBLDOBe7vYXQ:b-3jegzv) ([raw file](https://github.com/stratumn/go-indigocore/blob/8103fca14122b488c15bd215764178e5352ba940/tmpop/state.go#L68)):*
> ```Go
> 		loadValidatorFile(config.ValidatorFilename, validatorChan)
> 		var err error
> 		if watcher, err = fsnotify.NewWatcher(); err != nil {
> ```

Maybe NewState should start returning an error, because in case this goes wrong maybe the process needs to be fixed by the user?

---

*[tmstore/tmstore_test.go, line 61 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/345#-L5IVF8uDSK39D18bmft:-L5IVF8vX8C-sZHlplbT:bao9ebi) ([raw file](https://github.com/stratumn/go-indigocore/blob/8103fca14122b488c15bd215764178e5352ba940/tmstore/tmstore_test.go#L61)):*
> ```Go
> 	defer rulesInputFile.Close()
> 	content, err := ioutil.ReadAll(rulesInputFile)
> 	require.NoError(t, err, "Cannot read validator rule file %s", in)
> ```

nit: I think you need NoErrorf otherwise the error message won't be formatted properly

---

*[tmstore/tmstore_test.go, line 157 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/345#-L5IVVAoJ7wOALTAwFo4:-L5IVVApAfODEAEzVmsY:b-7y1jgo) ([raw file](https://github.com/stratumn/go-indigocore/blob/8103fca14122b488c15bd215764178e5352ba940/tmstore/tmstore_test.go#L157)):*
> ```Go
> 
> 			updateValidatorRulesFile(t, filepath.Join("testdata", "rules.new.json"), rulesFilename)
> 			time.Sleep(time.Second)
> ```

This looks like a very long time to sleep in a test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/345)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tmpop/state.go, line 68 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/345#-L5IUMrDT_lcmG_4U3mZ:-L5IYLm9J-jzNtnUwEdE:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/8103fca14122b488c15bd215764178e5352ba940/tmpop/state.go#L68)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Maybe NewState should start returning an error, because in case this goes wrong maybe the process needs to be fixed by the user?
</blockquote></details>

Done.

---

*[tmstore/tmstore_test.go, line 61 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/345#-L5IVF8uDSK39D18bmft:-L5IWuusJFAJCsG0wbDi:bb7m3jc) ([raw file](https://github.com/stratumn/go-indigocore/blob/8103fca14122b488c15bd215764178e5352ba940/tmstore/tmstore_test.go#L61)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: I think you need NoErrorf otherwise the error message won't be formatted properly
</blockquote></details>

oops

---

*[tmstore/tmstore_test.go, line 157 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/345#-L5IVVAoJ7wOALTAwFo4:-L5IX8lCzkXm98JOIveJ:byyaj3v) ([raw file](https://github.com/stratumn/go-indigocore/blob/8103fca14122b488c15bd215764178e5352ba940/tmstore/tmstore_test.go#L157)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

This looks like a very long time to sleep in a test
</blockquote></details>

Yes, I didn't want to tune the delay for desktop & travis for a non target solution.
I'll divide duration by 2

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/345)*

**Comment by t-bast** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tmstore/tmstore_test.go, line 157 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/345#-L5IVVAoJ7wOALTAwFo4:-L5IfbbB_9RwXKQo73js:b-v1d1w3) ([raw file](https://github.com/stratumn/go-indigocore/blob/8103fca14122b488c15bd215764178e5352ba940/tmstore/tmstore_test.go#L157)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Yes, I didn't want to tune the delay for desktop & travis for a non target solution.
I'll divide duration by 2
</blockquote></details>

But do you really need to sleep? Can't you wait on a channel with a condition?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/345)*

**Comment by t-bast** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/345#-:-L5InbeDe2_FBykAW6MZ:bnfp4nl)*

**Comment by simonvadee** [comment]
Reviewed 3 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tmpop/tmpop.go, line 173 at r2](https://reviewable.io:443/reviews/stratumn/go-indigocore/345#-L5K2Om2HM47VhE701IO:-L5K2Om2HM47VhE701IP:b-nwj3jm) ([raw file](https://github.com/stratumn/go-indigocore/blob/c5a6b5bbaba683a5f1ac643cc1b15826fc3d485c/tmpop/tmpop.go#L173)):*
> ```Go
> 	}
> 
> 	t.state.UpdateValidators()
> ```

do you think it would be worth running this in a goroutine instead of calling it every block ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/345)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tmpop/tmpop.go, line 173 at r2](https://reviewable.io:443/reviews/stratumn/go-indigocore/345#-L5K2Om2HM47VhE701IO:-L5K5f-LrJEzBQtt5GaJ:btcd4cq) ([raw file](https://github.com/stratumn/go-indigocore/blob/c5a6b5bbaba683a5f1ac643cc1b15826fc3d485c/tmpop/tmpop.go#L173)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

do you think it would be worth running this in a goroutine instead of calling it every block ?
</blockquote></details>

You are true, it should just reads new validators in a chan if there is new ones. I will load validator file in a goroutine.
It has to be done at `BeginBlock` to use the same validators for all segments of a same block.

---

*[tmstore/tmstore_test.go, line 157 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/345#-L5IVVAoJ7wOALTAwFo4:-L5K6U6k24jRIU3weCeR:b709emc) ([raw file](https://github.com/stratumn/go-indigocore/blob/8103fca14122b488c15bd215764178e5352ba940/tmstore/tmstore_test.go#L157)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

But do you really need to sleep? Can't you wait on a channel with a condition?
</blockquote></details>

As said IRL, it will be later when process designer will exist. It is temporary, we won't waste too much time on this point.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/345)*

**Comment by t-bast** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/345)*

**Comment by simonvadee** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tmpop/tmpop.go, line 173 at r2](https://reviewable.io:443/reviews/stratumn/go-indigocore/345#-L5K2Om2HM47VhE701IO:-L5KCwTu_It56NIEdGg6:beihsxc) ([raw file](https://github.com/stratumn/go-indigocore/blob/c5a6b5bbaba683a5f1ac643cc1b15826fc3d485c/tmpop/tmpop.go#L173)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

You are true, it should just reads new validators in a chan if there is new ones. I will load validator file in a goroutine.
It has to be done at `BeginBlock` to use the same validators for all segments of a same block.

</blockquote></details>

indeed :+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/345)*

**Comment by such** [comment]
Reviewed 4 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[tmpop/state.go, line 90 at r3](https://reviewable.io:443/reviews/stratumn/go-indigocore/345#-L5O_vaVbmzanbG9YFJX:-L5O_vaVbmzanbG9YFJY:bb55h7d) ([raw file](https://github.com/stratumn/go-indigocore/blob/a3892671e33b3ca2080d2e392ae486ca9c5a9117/tmpop/state.go#L90)):*
> ```Go
> 		log.Warnf("Could not load validator configuration: %s", err.Error())
> 	} else {
> 		select {
> ```

do we really need the `select` here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/345)*

**Comment by simonvadee** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/345#-:-L5OejXh-rL6Bnw9IfoD:bnfp4nl)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[tmpop/state.go, line 90 at r3](https://reviewable.io:443/reviews/stratumn/go-indigocore/345#-L5O_vaVbmzanbG9YFJX:-L5OfzFsnrkA50XbibW-:bl05zm6) ([raw file](https://github.com/stratumn/go-indigocore/blob/a3892671e33b3ca2080d2e392ae486ca9c5a9117/tmpop/state.go#L90)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

ok  never mind...
</blockquote></details>

Pushing data in chan embedded in a `select` allows to do not block (and do not send data) if the chan buffer is full.
In our case, it might be better to block because this call is now done in a goroutine (but chan is read each second, so it's ok for now). I'll modify it in a next PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/345)*

**Pull request merged**
