### PR TITLE
Small validator fix

### PR DESCRIPTION
**Pull request by simonvadee**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/370)

### CODE REVIEW

**Comment by alexppxela** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tmpop/state.go, line 105 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/370#-L7e2T011IuBbXS8RAS6:-L7e2T011IuBbXS8RAS7:b-jzbm6v) ([raw file](https://github.com/stratumn/go-indigocore/blob/7925242edf790a7af0acc000ec5f0207f6da24ee/tmpop/state.go#L105)):*
> ```Go
> 			return &ABCIError{
> 				CodeTypeValidation,
> 				fmt.Sprintf("Link validation rules failed %v: %v", link, err),
> ```

Why removing  link info?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/370)*

**Comment by simonvadee** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[tmpop/state.go, line 105 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/370#-L7e2T011IuBbXS8RAS6:-L7e3o143cPqm6Lp2hOu:bdrw0j3) ([raw file](https://github.com/stratumn/go-indigocore/blob/7925242edf790a7af0acc000ec5f0207f6da24ee/tmpop/state.go#L105)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Why removing  link info?
</blockquote></details>

Because the error message is explicit enough and it's too much data to display in the UI

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/370)*

**Comment by alexppxela** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/370#-:-L7e5VWmAqirBuaPfj2X:bnfp4nl)*

**Comment by t-bast** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[validator/configloader.go, line 28 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/370#-L7e6QiEgvZvpugZrarz:-L7e6QiEgvZvpugZras-:b-orn5e9) ([raw file](https://github.com/stratumn/go-indigocore/blob/a2c37f1e5441dc72b0591b7881d4d1721bad39cd/validator/configloader.go#L28)):*
> ```Go
> var (
> 	// ErrInvalidValidator is returned when the schema and the signatures are both missing in a validator.
> 	ErrInvalidValidator = errors.New("a validator requires a JSON schema, a signature or a transtion criteria to be valid")
> ```

nit: transition

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/370)*

**Comment by simonvadee** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[validator/configloader.go, line 28 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/370#-L7e6QiEgvZvpugZrarz:-L7e6ddd3C8WvlH8TDKI:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/a2c37f1e5441dc72b0591b7881d4d1721bad39cd/validator/configloader.go#L28)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: transition
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/370)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/370#-:-L7e7iM0m7mHF5biLyTl:bnfp4nl)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/370#-:-L7eDpcZ__6_1RTqyCr_:bnfp4nl)*

**Pull request merged**
