### PR TITLE
tmpop: validator set in proofs

### PR DESCRIPTION
**Pull request by t-bast**
Add validator set in tendermint proofs.
Tested with a byzantine node and fixed a few issues.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/364)

### CODE REVIEW

**Comment by t-bast** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/364#-:-L7Pvs1g1Vr6YqnRAyxc:bnfp4nl)*

**Comment by such** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cs/evidences/evidences.go, line 268 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364#-L7Q-caB0uwDI_TiWtqm:-L7Q-caB0uwDI_TiWtqn:bdwidf5) ([raw file](https://github.com/stratumn/go-indigocore/blob/c87526f8f8faa3f4ab4fc4450c3418c69addb146/cs/evidences/evidences.go#L268)):*
> ```Go
> 
> 	// We need 2/3 of the votes for the proof to be accepted.
> 	if 3*votesPower < 2*validatorSet.TotalVotingPower() {
> ```

I'm not sure that's correct.
If we have 3 nodes with 1 vote and only 2 nodes have voted then:
`(6 < 6) == false` => we'll return `true` even though we should return `false`. We must have strictly more than 2/3 of the votes.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364)*

**Comment by t-bast** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cs/evidences/evidences.go, line 268 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364#-L7Q-caB0uwDI_TiWtqm:-L7Q2McXCnGqGMFaH8ez:b-946xit) ([raw file](https://github.com/stratumn/go-indigocore/blob/c87526f8f8faa3f4ab4fc4450c3418c69addb146/cs/evidences/evidences.go#L268)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

I'm not sure that's correct.
If we have 3 nodes with 1 vote and only 2 nodes have voted then:
`(6 < 6) == false` => we'll return `true` even though we should return `false`. We must have strictly more than 2/3 of the votes.
</blockquote></details>

I thought the condition was that if you had exactly 2/3 then it worked...I'll double-check Tendermint's doc, thanks for raising this.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364)*

**Comment by t-bast** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364)*

**Comment by simonvadee** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cs/evidences/evidences.go, line 213 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/364#-L7Q-33QfEpLnRZS4VgN:-L7Q-33Rb7U8cO6_aNyZ:b-j80jc0) ([raw file](https://github.com/stratumn/go-indigocore/blob/c87526f8f8faa3f4ab4fc4450c3418c69addb146/cs/evidences/evidences.go#L213)):*
> ```Go
> }
> 
> // validateValidatorSet verifies that the signed header
> ```

nit: `headers`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/364#-:-L7Q3dlpP1q85geSaEI0:bnfp4nl)*

**Comment by t-bast** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cs/evidences/evidences.go, line 213 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364#-L7Q-33QfEpLnRZS4VgN:-L7Q54Uq6Z_v9nS7ClBP:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/c87526f8f8faa3f4ab4fc4450c3418c69addb146/cs/evidences/evidences.go#L213)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

nit: `headers`
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364#-:-L7Q9VGE3oxOB6BqOSrT:bnfp4nl)*

**Comment by such** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364#-:-L7QBtM99_thrJx6zmNt:bnfp4nl)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[cs/evidence_tendermint_test.go, line 62 at r3](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364#-L7QCZeAE49tNDUlhObC:-L7QCZeAE49tNDUlhObD:bdzqy2s) ([raw file](https://github.com/stratumn/go-indigocore/blob/776e8925411552aa8a0971d9b4d01ecd6b1bacf5/cs/evidence_tendermint_test.go#L62)):*
> ```Go
> 		Address:     pk3.Address(),
> 		PubKey:      pk3,
> 		VotingPower: 21,
> ```

changing this to 20 would test that we actually need 2/3+ (and not just 2/3)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364)*

**Comment by t-bast** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cs/evidence_tendermint_test.go, line 62 at r3](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364#-L7QCZeAE49tNDUlhObC:-L7QD7GF69GGTSEvBfTi:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/776e8925411552aa8a0971d9b4d01ecd6b1bacf5/cs/evidence_tendermint_test.go#L62)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

changing this to 20 would test that we actually need 2/3+ (and not just 2/3)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364)*

**Comment by such** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[cs/evidence_tendermint_test.go, line 62 at r3](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364#-L7QCZeAE49tNDUlhObC:-L7QF5Ay7AfaPfdM2iO6:bb7p5eq) ([raw file](https://github.com/stratumn/go-indigocore/blob/776e8925411552aa8a0971d9b4d01ecd6b1bacf5/cs/evidence_tendermint_test.go#L62)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364)*

**Comment by t-bast** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/364)*

**Pull request merged**
