### PR TITLE
cstesting: add test link builder

### PR DESCRIPTION
**Pull request by simonvadee**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/407)

### CODE REVIEW

**Comment by simonvadee** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[cs/cstesting/cstesting.go, line 32 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/407#-LAY9jNl832nVh9WvW8B:-LAYGzbO-y6xLPBGMok8:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/17a9d6515c1c6485a72fe7f55050c41b81df3055/cs/cstesting/cstesting.go#L32)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

nit: "createLink"
</blockquote></details>

Done.

---

*[validator/governance_test.go, line 243 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/407#-LAYCOCYB7D32B-ZvLx6:-LAYGv2rCQuR454AXNun:b1jxzi3) ([raw file](https://github.com/stratumn/go-indigocore/blob/17a9d6515c1c6485a72fe7f55050c41b81df3055/validator/governance_test.go#L243)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

you forgot `WithState`
</blockquote></details>

good catch, done.

---

*[validator/pki_test.go, line 69 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/407#-LAYCjL01uzBodsxjsv4:-LAYFqj74WSYfkARkj9T:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/17a9d6515c1c6485a72fe7f55050c41b81df3055/validator/pki_test.go#L69)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Hum. `link: link1,`
</blockquote></details>

Done.

---

*[validator/pki_test.go, line 75 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/407#-LAYCszE2jHVmV_OdN_z:-LAYFrP_CMXX4l8tPLpf:b-896fix) ([raw file](https://github.com/stratumn/go-indigocore/blob/17a9d6515c1c6485a72fe7f55050c41b81df3055/validator/pki_test.go#L75)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

same here and below
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/407)*

**Comment by alexppxela** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/407#-:-LAYI4th-zByQQ0XauBz:bnfp4nl)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 19 of 23 files at r1, 4 of 4 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[elasticsearchstore/elasticsearchstore_test.go, line 134 at r2](https://beta.reviewable.io/reviews/stratumn/go-indigocore/407#-LAYK-l99BW2DqLc5kBm:-LAYK-l99BW2DqLc5kBn:b-r2u2az) ([raw file](https://github.com/stratumn/go-indigocore/blob/0df44439ef5f6fcb30cbb69246dc2c008d94e162/elasticsearchstore/elasticsearchstore_test.go#L134)):*
> ```Go
> 		"common": "stratumn",
> 	}}
> 	link1 := cstesting.NewLinkBuilder().WithProcess("something crazy").WithTags([]string{"one", "two", "three"}).WithMapID("foo bar").WithState(state1).Build()
> ```

nit: some newlines would be helpful ;)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/407#-:-LAYKHTo1bDSUcb_DpfM:bnfp4nl)*

**Comment by such** [comment]
That's great!
:lgtm_strong: 

---

Reviewed 19 of 23 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/407#-:-LAY__x--UnW_rqY4vPy:b-tb7t44)*

**Comment by simonvadee** [comment]
Review status: 12 of 23 files reviewed at latest revision, 1 unresolved discussion.

---

*[elasticsearchstore/elasticsearchstore_test.go, line 134 at r2](https://beta.reviewable.io/reviews/stratumn/go-indigocore/407#-LAYK-l99BW2DqLc5kBm:-LAlQazYEInTmqAN9muX:bs7wuaw) ([raw file](https://github.com/stratumn/go-indigocore/blob/0df44439ef5f6fcb30cbb69246dc2c008d94e162/elasticsearchstore/elasticsearchstore_test.go#L134)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: some newlines would be helpful ;)
</blockquote></details>

Done !

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/407)*

**Comment by simonvadee** [comment]
Fixes #405

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 11 of 11 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/407#-:-LAlRJEO-OPZ48F_LDor:bnfp4nl)*

**Pull request merged**
