### PR TITLE
cs, validator: use stratumn/go-crypto

### PR DESCRIPTION
**Pull request by simonvadee**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/377)

### CODE REVIEW

**Comment by such** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[jsonhttp/jsonhttp.go, line 88 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/377#-L8hMeWL1R59y4_uVgpH:-L8hMeWL1R59y4_uVgpI:bhbj0ek) ([raw file](https://github.com/stratumn/go-indigocore/blob/5731faab53c4258ff3f274dea09d414af32948b1/jsonhttp/jsonhttp.go#L88)):*
> ```Go
> 		Addr:    config.Address,
> 		Handler: router,
> 		// Handler:        &ochttp.Handler{Handler: router},
> ```

are you sure about that?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/377)*

**Comment by t-bast** [comment]
Reviewed 20 of 21 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[jsonhttp/jsonhttp.go, line 88 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/377#-L8hMeWL1R59y4_uVgpH:-L8hNJrm3bSygibKI369:b-o5ieis) ([raw file](https://github.com/stratumn/go-indigocore/blob/5731faab53c4258ff3f274dea09d414af32948b1/jsonhttp/jsonhttp.go#L88)):*
<details><summary><i>Previously, such (Adrien Montfort) wrote…</i></summary><blockquote>

are you sure about that?
</blockquote></details>

Please don't commit that, it will be fixed tomorrow ;)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/377)*

**Comment by t-bast** [comment]
Reviewed 1 of 21 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/377)*

**Comment by simonvadee** [comment]
*[jsonhttp/jsonhttp.go, line 88 at r1](https://beta.reviewable.io/reviews/stratumn/go-indigocore/377#-L8hMeWL1R59y4_uVgpH:-L8hTjGbBWVXaPnxhp0-:brtzfox) ([raw file](https://github.com/stratumn/go-indigocore/blob/5731faab53c4258ff3f274dea09d414af32948b1/jsonhttp/jsonhttp.go#L88)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Please don't commit that, it will be fixed tomorrow ;)
</blockquote></details>

I didn't mean to commit that :)

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/377)*

**Comment by t-bast** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/377#-:-L8ka_Ck8z4oVU78qQoQ:bnfp4nl)*

**Pull request merged**
