### PR TITLE
ci: switch to golangci-lint

### PR DESCRIPTION
**Pull request by t-bast**
And fix a lot of warnings it generated :)
Looks like we had some missing error checks and a bit of dead code

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/421)

### CODE REVIEW

**Comment by alexppxela** [comment]
Cool golangci-lint is integrated into vscode!

This PR was very interesting to read ;)
:lgtm: 

---

Reviewed 59 of 59 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @t-bast and @simonvadee)

---

*[.editorconfig, line 11 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/421#-LFwev3e5vR77R56jGvI:-LFwev3fCJFDgw6bf181:bq0jvgv) ([raw file](https://github.com/stratumn/go-indigocore/blob/d8abb83fa6579d094bac6a6269d3f345630bb545/.editorconfig#L11)):*
> ```INI
> [*.go]
> indent_style = tab
> indent_size = 4
> ```

Spotted!!!
@stephan83 what do you think? :laughing: 

---

*[couchstore/api.go, line 84 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/421#-LFwjnJ16hF2hUGu_aPJ:-LFwjnJ16hF2hUGu_aPK:b-tx2xzd) ([raw file](https://github.com/stratumn/go-indigocore/blob/d8abb83fa6579d094bac6a6269d3f345630bb545/couchstore/api.go#L84)):*
> ```Go
> 
> // GetDatabases lists available databases.
> func (c *CouchStore) GetDatabases() ([]string, error) {
> ```

Why do you export these internal functions?

---


*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/421#-:-LFwfX7P9zg03Ou-BQn4:bj597i2)*

**Comment by t-bast** [comment]
It found a few interesting things, like the signal chan that needs to be buffered and the use of raw string in regexp.
It's quite fast and very useful, we should use this as our default linter :)

---

Review status: all files reviewed, 2 unresolved discussions (waiting on @t-bast and @simonvadee)

---

*[.editorconfig, line 11 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/421#-LFwev3e5vR77R56jGvI:-LFwnE3mAGf4vLhHrJUA:btyg5ig) ([raw file](https://github.com/stratumn/go-indigocore/blob/d8abb83fa6579d094bac6a6269d3f345630bb545/.editorconfig#L11)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Spotted!!!
@stephan83 what do you think? :laughing: 
</blockquote></details>

Heh ;)

---

*[couchstore/api.go, line 84 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/421#-LFwjnJ16hF2hUGu_aPJ:-LFwnFsH0VVhHS9r1SM4:bsyqam3) ([raw file](https://github.com/stratumn/go-indigocore/blob/d8abb83fa6579d094bac6a6269d3f345630bb545/couchstore/api.go#L84)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Why do you export these internal functions?
</blockquote></details>

Because otherwise they're spotted as dead code since the only place we use them is in the storetestcases...
Ideally we should move that to test helpers if we don't use this in the prod code

---


*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/421#-:-LFwnPje3J-0F97CMgBL:b3o4apa)*

**Comment by stephan83** [comment]
*[.editorconfig, line 11 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/421#-LFwev3e5vR77R56jGvI:-LFwny6u1MKdLF7XOxXx:b-26f9je) ([raw file](https://github.com/stratumn/go-indigocore/blob/d8abb83fa6579d094bac6a6269d3f345630bb545/.editorconfig#L11)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Heh ;)
</blockquote></details>

8 spaces should be hard-coded in the language syntax

---


*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/421)*

**Comment by alexppxela** [comment]
Review status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @simonvadee)

---

*[.editorconfig, line 11 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/421#-LFwev3e5vR77R56jGvI:-LFwoAkG-SoXWoOaZEMl:b-ve3yvb) ([raw file](https://github.com/stratumn/go-indigocore/blob/d8abb83fa6579d094bac6a6269d3f345630bb545/.editorconfig#L11)):*
<details><summary><i>Previously, stephan83 (stephan) wrote…</i></summary><blockquote>

8 spaces should be hard-coded in the language syntax
</blockquote></details>

:smile: 

---

*[couchstore/api.go, line 84 at r1](https://reviewable.io/reviews/stratumn/go-indigocore/421#-LFwjnJ16hF2hUGu_aPJ:-LFwo7Sy5UAJijkdY37L:b-8fx2u7) ([raw file](https://github.com/stratumn/go-indigocore/blob/d8abb83fa6579d094bac6a6269d3f345630bb545/couchstore/api.go#L84)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Because otherwise they're spotted as dead code since the only place we use them is in the storetestcases...
Ideally we should move that to test helpers if we don't use this in the prod code
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/421)*

**Pull request merged**
