### PR TITLE
Validator governance

### PR DESCRIPTION
**Pull request by alexppxela**
At startup rules are loaded
 - from file (if a rule has changed it is saved in store)
 - missing process rules are loaded from store
 - if one rule or more is loaded, validation is activated for all processes

When file is updated
 - new rule is taken into account
 - new rule is saved in store

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/go-indigocore/347)

### CODE REVIEW

**Comment by such** [comment]
Do we agree that it's just a first step and that in the end:
- we'll get rid of the rules file
- the governance manager will not write itself to the governance process, it will wait for a new segment to be added to this process by a client

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-:-L5isaAqJA_QHbnjtUaD:b-zftgyx)*

**Comment by t-bast** [comment]
Completely agree with Adrien, in the end we want to kind of reverse that process: the governance watcher will observe segments, not file updates and won't write to the store itself, just read from it.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[tmpop/state.go, line 43 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-L5ilAN-3uMpO5IjIysp:-L5ilAN00RcE_fxicuNn:bzbtpms) ([raw file](https://github.com/stratumn/go-indigocore/blob/1f4900efbb8da977469b1df22609a9ee7a1de297/tmpop/state.go#L43)):*
> ```Go
> 	checkedLinks       store.Batch
> 
> 	manager *validator.GovernanceManager
> ```

nit: manager doesn't tell you that the object is linked to governance...maybe "governance" or "govManager" would be more suited?

---

*[validator/governance.go, line 41 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-L5irXn8n-ywjDK4fl-7:-L5irXn8n-ywjDK4fl-8:b-g4wfs4) ([raw file](https://github.com/stratumn/go-indigocore/blob/1f4900efbb8da977469b1df22609a9ee7a1de297/validator/governance.go#L41)):*
> ```Go
> var defaultPagination = store.Pagination{
> 	Offset: 0,
> 	Limit:  1, // store.DefaultLimit,
> ```

Do you really want to fetch 1 by 1 or was it for your debugging?

---

*[validator/governance.go, line 100 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-L5is0a9HQnNl5qnqv5H:-L5is0a9HQnNl5qnqv5I:bezcyyw) ([raw file](https://github.com/stratumn/go-indigocore/blob/1f4900efbb8da977469b1df22609a9ee7a1de297/validator/governance.go#L100)):*
> ```Go
> 
> func (m *GovernanceManager) sendValidators() {
> 	var v4ch = make([]Validator, 0)
> ```

nit: you don't need the var, you can directly use short variable assignment

---

*[validator/governance.go, line 116 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-L5isEGiXP_pmyZausMa:-L5isEGjAKik1uKp08-9:b-eq2044) ([raw file](https://github.com/stratumn/go-indigocore/blob/1f4900efbb8da977469b1df22609a9ee7a1de297/validator/governance.go#L116)):*
> ```Go
> 		})
> 		if err != nil {
> 			log.Errorf("Cannot retrieve gouvernance segments: %+v", errors.WithStack(err))
> ```

nit: governance (same in other log messages)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-:-L5itEsG62QCaRxCe9-x:bp6xopj)*

**Comment by alexppxela** [comment]
- Yes, it is just a step. Rule file will be deleted when process designer will be useable.
- True for the second point too.

I will test writing rules in the tmstore adapter (not the underlying adapter), because in this PR, a file modification will affects only on TM node. 

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-:-L5itHm3-zlgfDQf-FSX:bgtuatu)*

**Comment by such** [comment]
OK cool
I don't think we need to wait for the process designer (rebranded "validations-ui" btw ;) ). We could just feed a rules.json file in the agent-ui for now. But we need to add the `_governance` process at the agent level so there's still some work ahead.
As long as we're on the same page we're good!

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-:-L5iv0wshg_EOU7C3fVp:by2ky3x)*

**Comment by alexppxela** [comment]
Perfect

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[tmpop/state.go, line 43 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-L5ilAN-3uMpO5IjIysp:-L5ivml9RivYRqBhR21F:bb74x83) ([raw file](https://github.com/stratumn/go-indigocore/blob/1f4900efbb8da977469b1df22609a9ee7a1de297/tmpop/state.go#L43)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: manager doesn't tell you that the object is linked to governance...maybe "governance" or "govManager" would be more suited?
</blockquote></details>

True

---

*[validator/governance.go, line 41 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-L5irXn8n-ywjDK4fl-7:-L5iufMkf41IvY4ugdUP:b-5zdf48) ([raw file](https://github.com/stratumn/go-indigocore/blob/1f4900efbb8da977469b1df22609a9ee7a1de297/validator/governance.go#L41)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

Do you really want to fetch 1 by 1 or was it for your debugging?
</blockquote></details>

Yes, it is the target, you just want to retrieve the last rule configuration (last segment ordered by priority)

---

*[validator/governance.go, line 100 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-L5is0a9HQnNl5qnqv5H:-L5ivSC0wa4xFYMCu20_:b2nign6) ([raw file](https://github.com/stratumn/go-indigocore/blob/1f4900efbb8da977469b1df22609a9ee7a1de297/validator/governance.go#L100)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: you don't need the var, you can directly use short variable assignment
</blockquote></details>

yes

---

*[validator/governance.go, line 116 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-L5isEGiXP_pmyZausMa:-L5ivAINXF16tsPVkLsE:b2nhpa7) ([raw file](https://github.com/stratumn/go-indigocore/blob/1f4900efbb8da977469b1df22609a9ee7a1de297/validator/governance.go#L116)):*
<details><summary><i>Previously, t-bast (Bastien Teinturier) wrote…</i></summary><blockquote>

nit: governance (same in other log messages)
</blockquote></details>

Thx

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-:-L5ivxnEy-lZkQzhU03W:b-j6u9bs)*

**Comment by t-bast** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[validator/governance.go, line 41 at r1](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-L5irXn8n-ywjDK4fl-7:-L5iwxNOasNexlVbIkao:b-mtgy2u) ([raw file](https://github.com/stratumn/go-indigocore/blob/1f4900efbb8da977469b1df22609a9ee7a1de297/validator/governance.go#L41)):*
<details><summary><i>Previously, alexppxela (Alexandre Thibault) wrote…</i></summary><blockquote>

Yes, it is the target, you just want to retrieve the last rule configuration (last segment ordered by priority)
</blockquote></details>

Ok makes sense.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/347)*

**Comment by t-bast** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-:-L5ix6AQM18na-l6EsgI:bnfp4nl)*

**Comment by simonvadee** [comment]
Reviewed 7 of 9 files at r1, 1 of 2 files at r2.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---

*[validator/governance.go, line 252 at r2](https://beta.reviewable.io/reviews/stratumn/go-indigocore/347#-L5j0mwy71_eJLQHTzx0:-L5j0mwy71_eJLQHTzx1:byipvx) ([raw file](https://github.com/stratumn/go-indigocore/blob/21b1bd70c85791c3e169098de34d3d03eed7a8bd/validator/governance.go#L252)):*
> ```Go
> 		"tags":     []interface{}{process, validatorTag},
> 		"pki":      schema.PKI,
> 		"types":    schema.Types,
> ```

any reason why are the validators stored in the link.meta instead of the state ? 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/347)*

**Comment by simonvadee** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/stratumn/go-indigocore/347)*

**Comment by alexppxela** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[validator/governance.go, line 252 at r2](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-L5j0mwy71_eJLQHTzx0:-L5nrOmPSU6fzA8wvbVB:buekp60) ([raw file](https://github.com/stratumn/go-indigocore/blob/21b1bd70c85791c3e169098de34d3d03eed7a8bd/validator/governance.go#L252)):*
<details><summary><i>Previously, simonvadee (Simon Vadée) wrote…</i></summary><blockquote>

any reason why are the validators stored in the link.meta instead of the state ? 
</blockquote></details>

Good point, it seems better.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/347)*

**Comment by simonvadee** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/stratumn/go-indigocore/347#-:-L5nu7bnGVZzhj4b7PIT:bnfp4nl)*

**Pull request merged**
